/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivityEvent {
  'id' : string,
  'title' : string,
  'userId' : UserId,
  'kind' : ActivityEventKind,
  'detail' : string,
  'timestamp' : Timestamp,
}
export type ActivityEventKind = { 'Login' : null } |
  { 'Registration' : null } |
  { 'Booking' : null } |
  { 'Enrollment' : null } |
  { 'Payment' : null };
export interface AdminCourse {
  'id' : CourseId,
  'status' : CourseStatus,
  'title' : string,
  'duration' : string,
  'imageBlob' : [] | [Uint8Array],
  'prerequisites' : Array<string>,
  'mode' : CourseMode,
  'createdAt' : Timestamp,
  'description' : string,
  'category' : string,
  'price' : bigint,
}
export interface AdminCourseInput {
  'status' : CourseStatus,
  'title' : string,
  'duration' : string,
  'imageData' : Uint8Array,
  'prerequisites' : Array<string>,
  'mode' : CourseMode,
  'description' : string,
  'category' : string,
  'price' : bigint,
}
export interface AdminPaymentEntry {
  'enrollmentId' : [] | [EnrollmentId],
  'bookingId' : [] | [BookingId],
  'clientName' : string,
  'order' : PaymentOrder,
  'clientPhone' : string,
  'serviceId' : [] | [string],
}
export interface AdminServiceCategory {
  'id' : ServiceId,
  'imageBlob' : [] | [Uint8Array],
  'subServices' : Array<SubService>,
  'icon' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
}
export interface AdminServiceInput {
  'imageData' : Uint8Array,
  'subServices' : Array<SubService>,
  'icon' : string,
  'name' : string,
  'description' : string,
}
export interface AnalyticsSummary {
  'pendingFeedbackCount' : bigint,
  'pendingBookings' : bigint,
  'totalEnrollments' : bigint,
  'emailLogCount' : bigint,
  'cancelledBookings' : bigint,
  'totalBookings' : bigint,
  'totalCourseRevenue' : bigint,
  'totalMultiServiceBookings' : bigint,
  'totalFeedback' : bigint,
  'confirmedBookings' : bigint,
  'completedBookings' : bigint,
  'totalUsers' : bigint,
  'totalRevenue' : bigint,
  'totalCmsEntries' : bigint,
  'revenueByService' : Array<ServiceRevenue>,
}
export type AssignmentStatus = { 'Delivered' : null } |
  { 'Approved' : null } |
  { 'InProgress' : null } |
  { 'Assigned' : null };
export interface BookingDetails {
  'serviceName' : string,
  'bookingId' : string,
  'date' : string,
  'time' : string,
  'clientEmail' : string,
  'totalAmount' : bigint,
  'clientPhone' : string,
  'location' : string,
}
export type BookingId = bigint;
export interface BookingInput {
  'duration' : string,
  'date' : string,
  'subService' : string,
  'notes' : [] | [string],
  'serviceId' : string,
  'location' : LocationType,
  'timeSlot' : TimeSlot,
}
export interface BookingRequest {
  'id' : BookingId,
  'status' : BookingStatus,
  'duration' : string,
  'rejectedReason' : [] | [string],
  'userId' : UserId,
  'date' : string,
  'createdAt' : Timestamp,
  'rescheduledDate' : [] | [string],
  'rescheduledTime' : [] | [string],
  'subService' : string,
  'notes' : [] | [string],
  'serviceId' : string,
  'location' : LocationType,
  'timeSlot' : TimeSlot,
}
export interface BookingSlot {
  'status' : SlotStatus,
  'date' : string,
  'timeSlot' : TimeSlot,
}
export type BookingStatus = { 'WorkDelivered' : null } |
  { 'Confirmed' : null } |
  { 'Rejected' : null } |
  { 'PaymentPending' : null } |
  { 'Cancelled' : null } |
  { 'Completed' : null } |
  { 'Pending' : null };
export interface Certificate {
  'id' : CertificateId,
  'verified' : boolean,
  'enrollmentId' : EnrollmentId,
  'studentName' : string,
  'code' : string,
  'issuedAt' : Timestamp,
  'courseName' : string,
  'courseId' : CourseId,
}
export type CertificateId = bigint;
export interface CmsContent {
  'key' : string,
  'contentType' : CmsContentType,
  'value' : string,
  'updatedAt' : Timestamp,
  'updatedBy' : UserId,
}
export type CmsContentType = { 'color' : null } |
  { 'text' : null } |
  { 'imageUrl' : null };
export interface Course {
  'id' : CourseId,
  'status' : CourseStatus,
  'title' : string,
  'duration' : string,
  'prerequisites' : Array<string>,
  'mode' : CourseMode,
  'description' : string,
  'imageUrl' : string,
  'category' : string,
  'price' : bigint,
}
export interface CourseEnrollment {
  'id' : EnrollmentId,
  'completedAt' : [] | [Timestamp],
  'paymentStatus' : PaymentStatus__1,
  'userId' : UserId,
  'progress' : bigint,
  'enrolledAt' : Timestamp,
  'certificateCode' : [] | [string],
  'courseId' : CourseId,
}
export type CourseId = bigint;
export interface CourseLessonProgress {
  'studentId' : UserId,
  'overallPercent' : bigint,
  'completedLessonIds' : Array<bigint>,
  'certificateEarned' : boolean,
  'currentLessonId' : [] | [bigint],
  'courseId' : CourseId,
}
export type CourseMode = { 'Online' : null } |
  { 'Offline' : null } |
  { 'Hybrid' : null };
export type CourseStatus = { 'Inactive' : null } |
  { 'Active' : null } |
  { 'ComingSoon' : null };
export interface Deliverable {
  'submittedAt' : Timestamp,
  'fileName' : string,
  'fileUrl' : string,
}
export interface EmailLog {
  'id' : bigint,
  'to' : string,
  'subject' : string,
  'body' : string,
  'createdAt' : Timestamp,
  'sent' : boolean,
  'relatedId' : [] | [string],
}
export type EnrollmentId = bigint;
export type ExternalBlob = Uint8Array;
export interface Feedback {
  'id' : bigint,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'responderComment' : [] | [string],
  'comment' : string,
  'targetType' : FeedbackTargetType,
  'rating' : bigint,
  'targetId' : string,
}
export type FeedbackTargetType = { 'Course' : null } |
  { 'Service' : null };
export type FileType = { 'Photo' : null } |
  { 'Video' : null };
export interface Lesson {
  'id' : bigint,
  'title' : string,
  'order' : bigint,
  'description' : string,
  'quizQuestions' : Array<QuizQuestion>,
  'youtubeUrl' : string,
  'courseId' : CourseId,
}
export interface LessonInput {
  'title' : string,
  'order' : bigint,
  'description' : string,
  'youtubeUrl' : string,
  'courseId' : CourseId,
}
export interface LessonProgress {
  'lessonId' : bigint,
  'completedAt' : [] | [bigint],
  'studentId' : UserId,
  'quizScore' : [] | [bigint],
  'videoWatched' : boolean,
  'quizPassed' : boolean,
}
export type LocationType = { 'Studio' : null } |
  { 'Custom' : string } |
  { 'Outdoor' : null } |
  { 'Indoor' : null };
export type LoginError = { 'lockedOut' : null } |
  { 'other' : string } |
  { 'pendingApproval' : null } |
  { 'notFound' : null } |
  { 'incorrectPassword' : null } |
  { 'suspended' : null };
export type MediaId = bigint;
export interface MediaInput {
  'title' : string,
  'serviceCategory' : string,
  'blob' : ExternalBlob,
  'fileType' : FileType,
}
export interface MediaItem {
  'id' : MediaId,
  'title' : string,
  'serviceCategory' : string,
  'featured' : boolean,
  'blob' : ExternalBlob,
  'date' : Timestamp,
  'fileType' : FileType,
  'uploadedBy' : UserId,
}
export interface MultiServiceBooking {
  'id' : BookingId,
  'status' : string,
  'userId' : UserId,
  'date' : string,
  'createdAt' : Timestamp,
  'totalAmount' : bigint,
  'notes' : [] | [string],
  'selectedServices' : Array<SelectedServiceItem>,
  'adminNotes' : [] | [string],
  'location' : string,
  'timeSlot' : string,
}
export interface MultiServiceBookingInput {
  'date' : string,
  'totalAmount' : bigint,
  'notes' : [] | [string],
  'selectedServices' : Array<SelectedServiceItem>,
  'location' : string,
  'timeSlot' : string,
}
export type NotificationId = bigint;
export interface NotificationRecord {
  'id' : NotificationId,
  'userId' : UserId,
  'notificationType' : NotificationType,
  'createdAt' : Timestamp,
  'read' : boolean,
  'message' : string,
}
export type NotificationType = { 'BookingCompleted' : null } |
  { 'CourseCompleted' : null } |
  { 'CourseEnrolled' : null } |
  { 'WorkDelivered' : null } |
  { 'GeneralInfo' : null } |
  { 'PaymentReceipt' : null } |
  { 'BookingConfirmed' : null } |
  { 'BookingReminder' : null };
export type PaymentAdminAction = { 'confirm' : null } |
  { 'adjustAmount' : bigint } |
  { 'refund' : null };
export type PaymentId = bigint;
export interface PaymentOrder {
  'id' : PaymentId,
  'signatureVerified' : boolean,
  'status' : PaymentStatus,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'referenceId' : string,
  'orderId' : string,
  'currency' : string,
  'paymentType' : PaymentType,
  'stripePaymentIntentId' : [] | [string],
  'checkoutUrl' : [] | [string],
  'stripeSessionId' : [] | [string],
  'amount' : bigint,
  'adminNotes' : [] | [string],
  'verifiedAt' : [] | [Timestamp],
  'paidAt' : [] | [Timestamp],
}
export interface PaymentOrderExtended {
  'id' : PaymentId,
  'razorpayPaymentId' : [] | [string],
  'status' : string,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'referenceId' : string,
  'orderId' : string,
  'razorpayOrderId' : string,
  'currency' : string,
  'paymentType' : string,
  'selectedServices' : Array<SelectedServiceItem>,
  'amount' : bigint,
  'adminNotes' : [] | [string],
  'paidAt' : [] | [Timestamp],
}
export interface PaymentReceiptDetails {
  'clientEmail' : string,
  'referenceId' : string,
  'currency' : string,
  'clientPhone' : string,
  'paymentId' : string,
  'amount' : bigint,
  'paidAt' : string,
}
export type PaymentStatus = { 'Failed' : null } |
  { 'Refunded' : null } |
  { 'Paid' : null } |
  { 'Created' : null };
export type PaymentStatus__1 = { 'PartiallyPaid' : null } |
  { 'FullyPaid' : null } |
  { 'Overdue' : null } |
  { 'Pending' : null };
export type PaymentType = { 'BookingBalance' : null } |
  { 'CertificateDownload' : null } |
  { 'CourseEnrollment' : null } |
  { 'BookingUpfront' : null };
export interface PaymentVerificationStatus {
  'signatureVerified' : boolean,
  'status' : PaymentStatus,
  'orderId' : string,
  'paymentId' : PaymentId,
  'stripePaymentIntentId' : [] | [string],
  'stripeSessionId' : [] | [string],
  'verifiedAt' : [] | [Timestamp],
}
export interface PublicProfile {
  'id' : UserId,
  'status' : UserStatus,
  'name' : string,
  'role' : UserRole,
  'studentDetails' : [] | [StudentDetails],
  'email' : string,
  'address' : [] | [string],
  'phone' : string,
  'registeredAt' : Timestamp,
}
export interface QuizQuestion {
  'id' : bigint,
  'lessonId' : bigint,
  'question' : string,
  'correctOptionIndex' : bigint,
  'options' : Array<string>,
}
export interface QuizQuestionInput {
  'lessonId' : bigint,
  'question' : string,
  'correctOptionIndex' : bigint,
  'options' : Array<string>,
}
export interface QuizResult {
  'lessonId' : bigint,
  'score' : bigint,
  'totalQuestions' : bigint,
  'passed' : boolean,
  'courseProgress' : CourseLessonProgress,
}
export interface SelectedServiceItem {
  'name' : string,
  'subServiceId' : string,
  'serviceId' : string,
  'price' : bigint,
}
export interface ServiceCategory {
  'id' : string,
  'subServices' : Array<SubService>,
  'icon' : string,
  'name' : string,
  'description' : string,
}
export type ServiceId = bigint;
export interface ServiceRevenue {
  'serviceName' : string,
  'revenue' : bigint,
  'serviceId' : string,
  'bookingCount' : bigint,
}
export type SlotStatus = { 'Available' : null } |
  { 'Taken' : null };
export interface StripeConfirmation {
  'stripePaymentIntentId' : string,
  'stripeSessionId' : string,
}
export interface StudentDetails {
  'learningMode' : string,
  'preferredSlot' : string,
  'courseType' : string,
}
export interface SubService { 'id' : string, 'name' : string }
export type TimeSlot = { 'Night' : null } |
  { 'Afternoon' : null } |
  { 'FullDay' : null } |
  { 'Morning' : null } |
  { 'Evening' : null } |
  { 'HalfDay' : null };
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserId = Principal;
export type UserRole = { 'Staff' : null } |
  { 'Client' : null } |
  { 'Student' : null } |
  { 'Receptionist' : null } |
  { 'Admin' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type UserStatus = { 'Active' : null } |
  { 'Suspended' : null } |
  { 'Rejected' : null } |
  { 'Pending' : null };
export interface WhatsAppLog {
  'id' : bigint,
  'createdAt' : Timestamp,
  'sent' : boolean,
  'message' : string,
  'phone' : string,
  'relatedId' : [] | [string],
}
export interface WorkAssignment {
  'id' : bigint,
  'status' : AssignmentStatus,
  'bookingId' : BookingId,
  'assignedAt' : Timestamp,
  'sessionDate' : string,
  'staffId' : UserId,
  'clientName' : string,
  'sessionType' : string,
  'notes' : [] | [string],
  'deliverables' : Array<Deliverable>,
}
export interface WorkAssignmentInput {
  'bookingId' : BookingId,
  'sessionDate' : string,
  'staffId' : UserId,
  'sessionType' : string,
  'notes' : [] | [string],
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addFeedback' : ActorMethod<
    [string, FeedbackTargetType, bigint, string],
    Feedback
  >,
  'addLesson' : ActorMethod<[LessonInput], Lesson>,
  'addQuizQuestion' : ActorMethod<[QuizQuestionInput], Lesson>,
  'adminAddCourse' : ActorMethod<[AdminCourseInput], AdminCourse>,
  'adminAddService' : ActorMethod<[AdminServiceInput], AdminServiceCategory>,
  'adminAdjustAmount' : ActorMethod<[PaymentId, bigint, string], boolean>,
  'adminConfirmPayment' : ActorMethod<[PaymentId, string], boolean>,
  'adminCreateUser' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      UserRole,
      [] | [string],
      [] | [StudentDetails],
    ],
    { 'ok' : PublicProfile } |
      { 'err' : string }
  >,
  'adminDeleteCourse' : ActorMethod<[CourseId], boolean>,
  'adminDeleteService' : ActorMethod<[ServiceId], boolean>,
  'adminGetAllCourseProgress' : ActorMethod<[], Array<CourseLessonProgress>>,
  'adminGetAllPayments' : ActorMethod<[], Array<PaymentOrder>>,
  'adminRefundPayment' : ActorMethod<[PaymentId, string], boolean>,
  'adminUpdateCourse' : ActorMethod<[CourseId, AdminCourseInput], boolean>,
  'adminUpdatePayment' : ActorMethod<
    [PaymentId, PaymentAdminAction, [] | [string]],
    boolean
  >,
  'adminUpdateService' : ActorMethod<[ServiceId, AdminServiceInput], boolean>,
  'approveUser' : ActorMethod<[UserId], { 'ok' : null } | { 'err' : string }>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'assignWork' : ActorMethod<[WorkAssignmentInput], WorkAssignment>,
  'bootstrapAdminProfile' : ActorMethod<
    [string, string, string, string],
    { 'ok' : PublicProfile } |
      { 'err' : string }
  >,
  'bulkGetUserProfiles' : ActorMethod<[Array<UserId>], Array<PublicProfile>>,
  'clearStaleEnrollments' : ActorMethod<[], bigint>,
  'confirmBooking' : ActorMethod<[BookingId], boolean>,
  'confirmPayment' : ActorMethod<[StripeConfirmation], boolean>,
  'createBookingRequest' : ActorMethod<[BookingInput], BookingRequest>,
  'createMultiServiceBooking' : ActorMethod<
    [MultiServiceBookingInput],
    BookingId
  >,
  'createPaymentOrder' : ActorMethod<
    [bigint, string, PaymentType],
    PaymentOrder
  >,
  'createSystemNotification' : ActorMethod<
    [UserId, string, NotificationType],
    NotificationRecord
  >,
  'deleteCmsContent' : ActorMethod<[string], undefined>,
  'deleteMedia' : ActorMethod<[MediaId], boolean>,
  'deleteSubServiceImage' : ActorMethod<[string, string], undefined>,
  'deleteUser' : ActorMethod<[UserId], { 'ok' : null } | { 'err' : string }>,
  'editLesson' : ActorMethod<[bigint, LessonInput], boolean>,
  'editQuizQuestion' : ActorMethod<[bigint, QuizQuestionInput], boolean>,
  'enrollCourse' : ActorMethod<[CourseId], CourseEnrollment>,
  'generateCertificate' : ActorMethod<[EnrollmentId], Certificate>,
  'getAdminBookings' : ActorMethod<
    [],
    Array<
      {
        'id' : BookingId,
        'status' : BookingStatus,
        'duration' : string,
        'clientName' : string,
        'rejectedReason' : [] | [string],
        'userId' : UserId,
        'date' : string,
        'createdAt' : Timestamp,
        'clientEmail' : string,
        'rescheduledDate' : [] | [string],
        'rescheduledTime' : [] | [string],
        'subService' : string,
        'notes' : [] | [string],
        'serviceId' : string,
        'location' : LocationType,
        'timeSlot' : TimeSlot,
      }
    >
  >,
  'getAdminCourseBlob' : ActorMethod<[CourseId], [] | [Uint8Array]>,
  'getAdminDashboardData' : ActorMethod<
    [],
    {
      'totalEnrollments' : bigint,
      'pendingUsers' : Array<PublicProfile>,
      'totalPayments' : bigint,
      'totalBookings' : bigint,
      'analytics' : AnalyticsSummary,
      'recentActivity' : Array<ActivityEvent>,
      'totalUsers' : bigint,
    }
  >,
  'getAdminEnrollments' : ActorMethod<
    [],
    Array<
      {
        'id' : EnrollmentId,
        'completedAt' : [] | [Timestamp],
        'studentEmail' : string,
        'paymentStatus' : PaymentStatus__1,
        'studentName' : string,
        'userId' : UserId,
        'progress' : bigint,
        'enrolledAt' : Timestamp,
        'courseName' : string,
        'certificateCode' : [] | [string],
        'courseId' : CourseId,
      }
    >
  >,
  'getAdminPaymentDashboard' : ActorMethod<[], Array<AdminPaymentEntry>>,
  'getAdminPayments' : ActorMethod<[], Array<PaymentOrderExtended>>,
  'getAdminServiceBlob' : ActorMethod<[ServiceId], [] | [Uint8Array]>,
  'getAdminUsers' : ActorMethod<[], Array<PublicProfile>>,
  'getAllActivityEvents' : ActorMethod<[], Array<ActivityEvent>>,
  'getAllAdminCourses' : ActorMethod<[], Array<AdminCourse>>,
  'getAllAdminServices' : ActorMethod<[], Array<AdminServiceCategory>>,
  'getAllBookings' : ActorMethod<[], Array<BookingRequest>>,
  'getAllCmsContent' : ActorMethod<[], Array<CmsContent>>,
  'getAllCourses' : ActorMethod<[], Array<Course>>,
  'getAllEnrollments' : ActorMethod<[], Array<CourseEnrollment>>,
  'getAllFeedback' : ActorMethod<[], Array<Feedback>>,
  'getAllPayments' : ActorMethod<[], Array<PaymentOrder>>,
  'getAllSubServiceImages' : ActorMethod<[], Array<[string, string]>>,
  'getAllUsers' : ActorMethod<[], Array<PublicProfile>>,
  'getAllWorkAssignments' : ActorMethod<[], Array<WorkAssignment>>,
  'getAnalytics' : ActorMethod<[], AnalyticsSummary>,
  'getBookingsByDate' : ActorMethod<[string], Array<BookingRequest>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [PublicProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getCertificate' : ActorMethod<[string], [] | [Certificate]>,
  'getCmsContent' : ActorMethod<[string], [] | [CmsContent]>,
  'getCourse' : ActorMethod<[CourseId], [] | [Course]>,
  'getCourseProgress' : ActorMethod<[CourseId], [] | [CourseLessonProgress]>,
  'getCourseProgressByEnrollment' : ActorMethod<
    [EnrollmentId],
    [] | [CourseLessonProgress]
  >,
  'getEmailLogs' : ActorMethod<[], Array<EmailLog>>,
  'getEnrollmentById' : ActorMethod<[EnrollmentId], [] | [CourseEnrollment]>,
  'getEnrollmentsByCourse' : ActorMethod<
    [CourseId],
    Array<
      {
        'progress' : [] | [CourseLessonProgress],
        'enrollment' : CourseEnrollment,
      }
    >
  >,
  'getFeedbackForTarget' : ActorMethod<[string], Array<Feedback>>,
  'getLessonProgressForCourse' : ActorMethod<[CourseId], Array<LessonProgress>>,
  'getLessons' : ActorMethod<[CourseId], Array<Lesson>>,
  'getMediaItems' : ActorMethod<[[] | [string]], Array<MediaItem>>,
  'getMyAssignedWork' : ActorMethod<[], Array<WorkAssignment>>,
  'getMyBookings' : ActorMethod<[], Array<BookingRequest>>,
  'getMyCertificate' : ActorMethod<[EnrollmentId], [] | [Certificate]>,
  'getMyEnrollments' : ActorMethod<[], Array<CourseEnrollment>>,
  'getMyFeedback' : ActorMethod<[], Array<Feedback>>,
  'getMyMultiServiceBookings' : ActorMethod<[], Array<MultiServiceBooking>>,
  'getMyNotifications' : ActorMethod<[], Array<NotificationRecord>>,
  'getMyPayments' : ActorMethod<[], Array<PaymentOrder>>,
  'getMyProfile' : ActorMethod<[], [] | [PublicProfile]>,
  'getMyUploadedWork' : ActorMethod<[], Array<WorkAssignment>>,
  'getPaymentDetails' : ActorMethod<[PaymentId], [] | [PaymentOrderExtended]>,
  'getPaymentStatus' : ActorMethod<[bigint], [] | [PaymentVerificationStatus]>,
  'getPublicCalendar' : ActorMethod<[], Array<BookingSlot>>,
  'getPublicProfile' : ActorMethod<[string], [] | [PublicProfile]>,
  'getRecentActivity' : ActorMethod<[], Array<ActivityEvent>>,
  'getServiceCategories' : ActorMethod<[], Array<ServiceCategory>>,
  'getStripeConfig' : ActorMethod<
    [],
    { 'secretKey' : string, 'configured' : boolean, 'publishableKey' : string }
  >,
  'getSubServiceImage' : ActorMethod<[string, string], [] | [string]>,
  'getSubServiceImageBlob' : ActorMethod<[string, string], [] | [Uint8Array]>,
  'getWhatsAppLogs' : ActorMethod<[], Array<WhatsAppLog>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCertificatePaymentDone' : ActorMethod<[EnrollmentId], boolean>,
  'listMyPayments' : ActorMethod<[], Array<PaymentOrder>>,
  'listPendingUsers' : ActorMethod<[], Array<PublicProfile>>,
  'loginByEmail' : ActorMethod<
    [string, string],
    { 'ok' : PublicProfile } |
      { 'err' : LoginError }
  >,
  'loginByIdentifier' : ActorMethod<
    [string, string],
    { 'ok' : PublicProfile } |
      { 'err' : LoginError }
  >,
  'manageUser' : ActorMethod<[UserId, string], boolean>,
  'markCourseComplete' : ActorMethod<
    [EnrollmentId],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'markEnrollmentPaid' : ActorMethod<[EnrollmentId], boolean>,
  'markNotificationRead' : ActorMethod<[NotificationId], boolean>,
  'markVideoWatched' : ActorMethod<[bigint], LessonProgress>,
  'markWorkDelivered' : ActorMethod<[BookingId], boolean>,
  'ping' : ActorMethod<
    [],
    {
      'status' : string,
      'userCount' : bigint,
      'bookingCount' : bigint,
      'enrollmentCount' : bigint,
    }
  >,
  'register' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      UserRole,
      [] | [string],
      [] | [Uint8Array],
      [] | [StudentDetails],
    ],
    { 'ok' : PublicProfile } |
      { 'err' : string }
  >,
  'rejectBooking' : ActorMethod<[BookingId, string], boolean>,
  'rejectUser' : ActorMethod<[UserId], { 'ok' : null } | { 'err' : string }>,
  'removeLesson' : ActorMethod<[bigint], boolean>,
  'removeQuizQuestion' : ActorMethod<[bigint], boolean>,
  'rescheduleBooking' : ActorMethod<[BookingId, string, string], boolean>,
  'respondToFeedback' : ActorMethod<[bigint, string], boolean>,
  'saveCallerUserProfile' : ActorMethod<[string, string, UserRole], undefined>,
  'sendBookingConfirmation' : ActorMethod<[UserId, BookingDetails], boolean>,
  'sendCompletionMessage' : ActorMethod<
    [UserId, BookingDetails, string],
    boolean
  >,
  'sendPaymentReceipt' : ActorMethod<[UserId, PaymentReceiptDetails], boolean>,
  'sendProgressReminder' : ActorMethod<[UserId, BookingDetails], boolean>,
  'setCmsContent' : ActorMethod<[string, string, CmsContentType], undefined>,
  'setFeatured' : ActorMethod<[MediaId, boolean], boolean>,
  'setStripeKeys' : ActorMethod<[string, string], boolean>,
  'setSubServiceImage' : ActorMethod<[string, string, string], undefined>,
  'submitDeliverable' : ActorMethod<[bigint, string, string], boolean>,
  'submitQuiz' : ActorMethod<
    [bigint, Array<bigint>],
    { 'ok' : QuizResult } |
      { 'err' : string }
  >,
  'testStripeConnection' : ActorMethod<
    [],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'transformWhatsApp' : ActorMethod<
    [TransformationInput],
    TransformationOutput
  >,
  'triggerPaymentRequest' : ActorMethod<[BookingId, string], string>,
  'updateAssignmentStatus' : ActorMethod<[bigint, AssignmentStatus], boolean>,
  'updateCourseMode' : ActorMethod<[CourseId, CourseMode], boolean>,
  'updateCourseProgress' : ActorMethod<[CourseId, boolean], boolean>,
  'updateProfile' : ActorMethod<[string, string, [] | [string]], boolean>,
  'uploadMedia' : ActorMethod<[MediaInput], MediaItem>,
  'uploadSubServiceImage' : ActorMethod<
    [string, string, Uint8Array],
    undefined
  >,
  'verifyCertificate' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];