/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const FeedbackTargetType = IDL.Variant({
  'Course' : IDL.Null,
  'Service' : IDL.Null,
});
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const Feedback = IDL.Record({
  'id' : IDL.Nat,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'responderComment' : IDL.Opt(IDL.Text),
  'comment' : IDL.Text,
  'targetType' : FeedbackTargetType,
  'rating' : IDL.Nat,
  'targetId' : IDL.Text,
});
export const CourseId = IDL.Nat;
export const LessonInput = IDL.Record({
  'title' : IDL.Text,
  'order' : IDL.Nat,
  'description' : IDL.Text,
  'youtubeUrl' : IDL.Text,
  'courseId' : CourseId,
});
export const QuizQuestion = IDL.Record({
  'id' : IDL.Nat,
  'lessonId' : IDL.Nat,
  'question' : IDL.Text,
  'correctOptionIndex' : IDL.Nat,
  'options' : IDL.Vec(IDL.Text),
});
export const Lesson = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'order' : IDL.Nat,
  'description' : IDL.Text,
  'quizQuestions' : IDL.Vec(QuizQuestion),
  'youtubeUrl' : IDL.Text,
  'courseId' : CourseId,
});
export const QuizQuestionInput = IDL.Record({
  'lessonId' : IDL.Nat,
  'question' : IDL.Text,
  'correctOptionIndex' : IDL.Nat,
  'options' : IDL.Vec(IDL.Text),
});
export const CourseStatus = IDL.Variant({
  'Inactive' : IDL.Null,
  'Active' : IDL.Null,
  'ComingSoon' : IDL.Null,
});
export const CourseMode = IDL.Variant({
  'Online' : IDL.Null,
  'Offline' : IDL.Null,
  'Hybrid' : IDL.Null,
});
export const AdminCourseInput = IDL.Record({
  'status' : CourseStatus,
  'title' : IDL.Text,
  'duration' : IDL.Text,
  'imageData' : IDL.Vec(IDL.Nat8),
  'prerequisites' : IDL.Vec(IDL.Text),
  'mode' : CourseMode,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const AdminCourse = IDL.Record({
  'id' : CourseId,
  'status' : CourseStatus,
  'title' : IDL.Text,
  'duration' : IDL.Text,
  'imageBlob' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'prerequisites' : IDL.Vec(IDL.Text),
  'mode' : CourseMode,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const SubService = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
export const AdminServiceInput = IDL.Record({
  'imageData' : IDL.Vec(IDL.Nat8),
  'subServices' : IDL.Vec(SubService),
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const ServiceId = IDL.Nat;
export const AdminServiceCategory = IDL.Record({
  'id' : ServiceId,
  'imageBlob' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'subServices' : IDL.Vec(SubService),
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
});
export const PaymentId = IDL.Nat;
export const UserRole = IDL.Variant({
  'Staff' : IDL.Null,
  'Client' : IDL.Null,
  'Student' : IDL.Null,
  'Receptionist' : IDL.Null,
  'Admin' : IDL.Null,
});
export const StudentDetails = IDL.Record({
  'learningMode' : IDL.Text,
  'preferredSlot' : IDL.Text,
  'courseType' : IDL.Text,
});
export const UserStatus = IDL.Variant({
  'Active' : IDL.Null,
  'Suspended' : IDL.Null,
  'Rejected' : IDL.Null,
  'Pending' : IDL.Null,
});
export const PublicProfile = IDL.Record({
  'id' : UserId,
  'status' : UserStatus,
  'name' : IDL.Text,
  'role' : UserRole,
  'studentDetails' : IDL.Opt(StudentDetails),
  'email' : IDL.Text,
  'address' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
  'registeredAt' : Timestamp,
});
export const CourseLessonProgress = IDL.Record({
  'studentId' : UserId,
  'overallPercent' : IDL.Nat,
  'completedLessonIds' : IDL.Vec(IDL.Nat),
  'certificateEarned' : IDL.Bool,
  'currentLessonId' : IDL.Opt(IDL.Nat),
  'courseId' : CourseId,
});
export const PaymentStatus = IDL.Variant({
  'Failed' : IDL.Null,
  'Refunded' : IDL.Null,
  'Paid' : IDL.Null,
  'Created' : IDL.Null,
});
export const PaymentType = IDL.Variant({
  'BookingBalance' : IDL.Null,
  'CertificateDownload' : IDL.Null,
  'CourseEnrollment' : IDL.Null,
  'BookingUpfront' : IDL.Null,
});
export const PaymentOrder = IDL.Record({
  'id' : PaymentId,
  'signatureVerified' : IDL.Bool,
  'status' : PaymentStatus,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'referenceId' : IDL.Text,
  'orderId' : IDL.Text,
  'currency' : IDL.Text,
  'paymentType' : PaymentType,
  'stripePaymentIntentId' : IDL.Opt(IDL.Text),
  'checkoutUrl' : IDL.Opt(IDL.Text),
  'stripeSessionId' : IDL.Opt(IDL.Text),
  'amount' : IDL.Nat,
  'adminNotes' : IDL.Opt(IDL.Text),
  'verifiedAt' : IDL.Opt(Timestamp),
  'paidAt' : IDL.Opt(Timestamp),
});
export const PaymentAdminAction = IDL.Variant({
  'confirm' : IDL.Null,
  'adjustAmount' : IDL.Nat,
  'refund' : IDL.Null,
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BookingId = IDL.Nat;
export const WorkAssignmentInput = IDL.Record({
  'bookingId' : BookingId,
  'sessionDate' : IDL.Text,
  'staffId' : UserId,
  'sessionType' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
});
export const AssignmentStatus = IDL.Variant({
  'Delivered' : IDL.Null,
  'Approved' : IDL.Null,
  'InProgress' : IDL.Null,
  'Assigned' : IDL.Null,
});
export const Deliverable = IDL.Record({
  'submittedAt' : Timestamp,
  'fileName' : IDL.Text,
  'fileUrl' : IDL.Text,
});
export const WorkAssignment = IDL.Record({
  'id' : IDL.Nat,
  'status' : AssignmentStatus,
  'bookingId' : BookingId,
  'assignedAt' : Timestamp,
  'sessionDate' : IDL.Text,
  'staffId' : UserId,
  'clientName' : IDL.Text,
  'sessionType' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'deliverables' : IDL.Vec(Deliverable),
});
export const StripeConfirmation = IDL.Record({
  'stripePaymentIntentId' : IDL.Text,
  'stripeSessionId' : IDL.Text,
});
export const LocationType = IDL.Variant({
  'Studio' : IDL.Null,
  'Custom' : IDL.Text,
  'Outdoor' : IDL.Null,
  'Indoor' : IDL.Null,
});
export const TimeSlot = IDL.Variant({
  'Night' : IDL.Null,
  'Afternoon' : IDL.Null,
  'FullDay' : IDL.Null,
  'Morning' : IDL.Null,
  'Evening' : IDL.Null,
  'HalfDay' : IDL.Null,
});
export const BookingInput = IDL.Record({
  'duration' : IDL.Text,
  'date' : IDL.Text,
  'subService' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'serviceId' : IDL.Text,
  'location' : LocationType,
  'timeSlot' : TimeSlot,
});
export const BookingStatus = IDL.Variant({
  'WorkDelivered' : IDL.Null,
  'Confirmed' : IDL.Null,
  'Rejected' : IDL.Null,
  'PaymentPending' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Completed' : IDL.Null,
  'Pending' : IDL.Null,
});
export const BookingRequest = IDL.Record({
  'id' : BookingId,
  'status' : BookingStatus,
  'duration' : IDL.Text,
  'rejectedReason' : IDL.Opt(IDL.Text),
  'userId' : UserId,
  'date' : IDL.Text,
  'createdAt' : Timestamp,
  'rescheduledDate' : IDL.Opt(IDL.Text),
  'rescheduledTime' : IDL.Opt(IDL.Text),
  'subService' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'serviceId' : IDL.Text,
  'location' : LocationType,
  'timeSlot' : TimeSlot,
});
export const SelectedServiceItem = IDL.Record({
  'name' : IDL.Text,
  'subServiceId' : IDL.Text,
  'serviceId' : IDL.Text,
  'price' : IDL.Nat,
});
export const MultiServiceBookingInput = IDL.Record({
  'date' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'notes' : IDL.Opt(IDL.Text),
  'selectedServices' : IDL.Vec(SelectedServiceItem),
  'location' : IDL.Text,
  'timeSlot' : IDL.Text,
});
export const NotificationType = IDL.Variant({
  'BookingCompleted' : IDL.Null,
  'CourseCompleted' : IDL.Null,
  'CourseEnrolled' : IDL.Null,
  'WorkDelivered' : IDL.Null,
  'GeneralInfo' : IDL.Null,
  'PaymentReceipt' : IDL.Null,
  'BookingConfirmed' : IDL.Null,
  'BookingReminder' : IDL.Null,
});
export const NotificationId = IDL.Nat;
export const NotificationRecord = IDL.Record({
  'id' : NotificationId,
  'userId' : UserId,
  'notificationType' : NotificationType,
  'createdAt' : Timestamp,
  'read' : IDL.Bool,
  'message' : IDL.Text,
});
export const MediaId = IDL.Nat;
export const EnrollmentId = IDL.Nat;
export const PaymentStatus__1 = IDL.Variant({
  'PartiallyPaid' : IDL.Null,
  'FullyPaid' : IDL.Null,
  'Overdue' : IDL.Null,
  'Pending' : IDL.Null,
});
export const CourseEnrollment = IDL.Record({
  'id' : EnrollmentId,
  'completedAt' : IDL.Opt(Timestamp),
  'paymentStatus' : PaymentStatus__1,
  'userId' : UserId,
  'progress' : IDL.Nat,
  'enrolledAt' : Timestamp,
  'certificateCode' : IDL.Opt(IDL.Text),
  'courseId' : CourseId,
});
export const CertificateId = IDL.Nat;
export const Certificate = IDL.Record({
  'id' : CertificateId,
  'verified' : IDL.Bool,
  'enrollmentId' : EnrollmentId,
  'studentName' : IDL.Text,
  'code' : IDL.Text,
  'issuedAt' : Timestamp,
  'courseName' : IDL.Text,
  'courseId' : CourseId,
});
export const ServiceRevenue = IDL.Record({
  'serviceName' : IDL.Text,
  'revenue' : IDL.Nat,
  'serviceId' : IDL.Text,
  'bookingCount' : IDL.Nat,
});
export const AnalyticsSummary = IDL.Record({
  'pendingFeedbackCount' : IDL.Nat,
  'pendingBookings' : IDL.Nat,
  'totalEnrollments' : IDL.Nat,
  'emailLogCount' : IDL.Nat,
  'cancelledBookings' : IDL.Nat,
  'totalBookings' : IDL.Nat,
  'totalCourseRevenue' : IDL.Nat,
  'totalMultiServiceBookings' : IDL.Nat,
  'totalFeedback' : IDL.Nat,
  'confirmedBookings' : IDL.Nat,
  'completedBookings' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
  'totalCmsEntries' : IDL.Nat,
  'revenueByService' : IDL.Vec(ServiceRevenue),
});
export const ActivityEventKind = IDL.Variant({
  'Login' : IDL.Null,
  'Registration' : IDL.Null,
  'Booking' : IDL.Null,
  'Enrollment' : IDL.Null,
  'Payment' : IDL.Null,
});
export const ActivityEvent = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'userId' : UserId,
  'kind' : ActivityEventKind,
  'detail' : IDL.Text,
  'timestamp' : Timestamp,
});
export const AdminPaymentEntry = IDL.Record({
  'enrollmentId' : IDL.Opt(EnrollmentId),
  'bookingId' : IDL.Opt(BookingId),
  'clientName' : IDL.Text,
  'order' : PaymentOrder,
  'clientPhone' : IDL.Text,
  'serviceId' : IDL.Opt(IDL.Text),
});
export const PaymentOrderExtended = IDL.Record({
  'id' : PaymentId,
  'razorpayPaymentId' : IDL.Opt(IDL.Text),
  'status' : IDL.Text,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'referenceId' : IDL.Text,
  'orderId' : IDL.Text,
  'razorpayOrderId' : IDL.Text,
  'currency' : IDL.Text,
  'paymentType' : IDL.Text,
  'selectedServices' : IDL.Vec(SelectedServiceItem),
  'amount' : IDL.Nat,
  'adminNotes' : IDL.Opt(IDL.Text),
  'paidAt' : IDL.Opt(Timestamp),
});
export const CmsContentType = IDL.Variant({
  'color' : IDL.Null,
  'text' : IDL.Null,
  'imageUrl' : IDL.Null,
});
export const CmsContent = IDL.Record({
  'key' : IDL.Text,
  'contentType' : CmsContentType,
  'value' : IDL.Text,
  'updatedAt' : Timestamp,
  'updatedBy' : UserId,
});
export const Course = IDL.Record({
  'id' : CourseId,
  'status' : CourseStatus,
  'title' : IDL.Text,
  'duration' : IDL.Text,
  'prerequisites' : IDL.Vec(IDL.Text),
  'mode' : CourseMode,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const EmailLog = IDL.Record({
  'id' : IDL.Nat,
  'to' : IDL.Text,
  'subject' : IDL.Text,
  'body' : IDL.Text,
  'createdAt' : Timestamp,
  'sent' : IDL.Bool,
  'relatedId' : IDL.Opt(IDL.Text),
});
export const LessonProgress = IDL.Record({
  'lessonId' : IDL.Nat,
  'completedAt' : IDL.Opt(IDL.Int),
  'studentId' : UserId,
  'quizScore' : IDL.Opt(IDL.Nat),
  'videoWatched' : IDL.Bool,
  'quizPassed' : IDL.Bool,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const FileType = IDL.Variant({ 'Photo' : IDL.Null, 'Video' : IDL.Null });
export const MediaItem = IDL.Record({
  'id' : MediaId,
  'title' : IDL.Text,
  'serviceCategory' : IDL.Text,
  'featured' : IDL.Bool,
  'blob' : ExternalBlob,
  'date' : Timestamp,
  'fileType' : FileType,
  'uploadedBy' : UserId,
});
export const MultiServiceBooking = IDL.Record({
  'id' : BookingId,
  'status' : IDL.Text,
  'userId' : UserId,
  'date' : IDL.Text,
  'createdAt' : Timestamp,
  'totalAmount' : IDL.Nat,
  'notes' : IDL.Opt(IDL.Text),
  'selectedServices' : IDL.Vec(SelectedServiceItem),
  'adminNotes' : IDL.Opt(IDL.Text),
  'location' : IDL.Text,
  'timeSlot' : IDL.Text,
});
export const PaymentVerificationStatus = IDL.Record({
  'signatureVerified' : IDL.Bool,
  'status' : PaymentStatus,
  'orderId' : IDL.Text,
  'paymentId' : PaymentId,
  'stripePaymentIntentId' : IDL.Opt(IDL.Text),
  'stripeSessionId' : IDL.Opt(IDL.Text),
  'verifiedAt' : IDL.Opt(Timestamp),
});
export const SlotStatus = IDL.Variant({
  'Available' : IDL.Null,
  'Taken' : IDL.Null,
});
export const BookingSlot = IDL.Record({
  'status' : SlotStatus,
  'date' : IDL.Text,
  'timeSlot' : TimeSlot,
});
export const ServiceCategory = IDL.Record({
  'id' : IDL.Text,
  'subServices' : IDL.Vec(SubService),
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const WhatsAppLog = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : Timestamp,
  'sent' : IDL.Bool,
  'message' : IDL.Text,
  'phone' : IDL.Text,
  'relatedId' : IDL.Opt(IDL.Text),
});
export const LoginError = IDL.Variant({
  'lockedOut' : IDL.Null,
  'other' : IDL.Text,
  'pendingApproval' : IDL.Null,
  'notFound' : IDL.Null,
  'incorrectPassword' : IDL.Null,
  'suspended' : IDL.Null,
});
export const BookingDetails = IDL.Record({
  'serviceName' : IDL.Text,
  'bookingId' : IDL.Text,
  'date' : IDL.Text,
  'time' : IDL.Text,
  'clientEmail' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'clientPhone' : IDL.Text,
  'location' : IDL.Text,
});
export const PaymentReceiptDetails = IDL.Record({
  'clientEmail' : IDL.Text,
  'referenceId' : IDL.Text,
  'currency' : IDL.Text,
  'clientPhone' : IDL.Text,
  'paymentId' : IDL.Text,
  'amount' : IDL.Nat,
  'paidAt' : IDL.Text,
});
export const QuizResult = IDL.Record({
  'lessonId' : IDL.Nat,
  'score' : IDL.Nat,
  'totalQuestions' : IDL.Nat,
  'passed' : IDL.Bool,
  'courseProgress' : CourseLessonProgress,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const MediaInput = IDL.Record({
  'title' : IDL.Text,
  'serviceCategory' : IDL.Text,
  'blob' : ExternalBlob,
  'fileType' : FileType,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addFeedback' : IDL.Func(
      [IDL.Text, FeedbackTargetType, IDL.Nat, IDL.Text],
      [Feedback],
      [],
    ),
  'addLesson' : IDL.Func([LessonInput], [Lesson], []),
  'addQuizQuestion' : IDL.Func([QuizQuestionInput], [Lesson], []),
  'adminAddCourse' : IDL.Func([AdminCourseInput], [AdminCourse], []),
  'adminAddService' : IDL.Func([AdminServiceInput], [AdminServiceCategory], []),
  'adminAdjustAmount' : IDL.Func(
      [PaymentId, IDL.Nat, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'adminConfirmPayment' : IDL.Func([PaymentId, IDL.Text], [IDL.Bool], []),
  'adminCreateUser' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        UserRole,
        IDL.Opt(IDL.Text),
        IDL.Opt(StudentDetails),
      ],
      [IDL.Variant({ 'ok' : PublicProfile, 'err' : IDL.Text })],
      [],
    ),
  'adminDeleteCourse' : IDL.Func([CourseId], [IDL.Bool], []),
  'adminDeleteService' : IDL.Func([ServiceId], [IDL.Bool], []),
  'adminGetAllCourseProgress' : IDL.Func(
      [],
      [IDL.Vec(CourseLessonProgress)],
      ['query'],
    ),
  'adminGetAllPayments' : IDL.Func([], [IDL.Vec(PaymentOrder)], ['query']),
  'adminRefundPayment' : IDL.Func([PaymentId, IDL.Text], [IDL.Bool], []),
  'adminUpdateCourse' : IDL.Func([CourseId, AdminCourseInput], [IDL.Bool], []),
  'adminUpdatePayment' : IDL.Func(
      [PaymentId, PaymentAdminAction, IDL.Opt(IDL.Text)],
      [IDL.Bool],
      [],
    ),
  'adminUpdateService' : IDL.Func(
      [ServiceId, AdminServiceInput],
      [IDL.Bool],
      [],
    ),
  'approveUser' : IDL.Func(
      [UserId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'assignWork' : IDL.Func([WorkAssignmentInput], [WorkAssignment], []),
  'bootstrapAdminProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : PublicProfile, 'err' : IDL.Text })],
      [],
    ),
  'bulkGetUserProfiles' : IDL.Func(
      [IDL.Vec(UserId)],
      [IDL.Vec(PublicProfile)],
      ['query'],
    ),
  'clearStaleEnrollments' : IDL.Func([], [IDL.Nat], []),
  'confirmBooking' : IDL.Func([BookingId], [IDL.Bool], []),
  'confirmPayment' : IDL.Func([StripeConfirmation], [IDL.Bool], []),
  'createBookingRequest' : IDL.Func([BookingInput], [BookingRequest], []),
  'createMultiServiceBooking' : IDL.Func(
      [MultiServiceBookingInput],
      [BookingId],
      [],
    ),
  'createPaymentOrder' : IDL.Func(
      [IDL.Nat, IDL.Text, PaymentType],
      [PaymentOrder],
      [],
    ),
  'createSystemNotification' : IDL.Func(
      [UserId, IDL.Text, NotificationType],
      [NotificationRecord],
      [],
    ),
  'deleteCmsContent' : IDL.Func([IDL.Text], [], []),
  'deleteMedia' : IDL.Func([MediaId], [IDL.Bool], []),
  'deleteSubServiceImage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteUser' : IDL.Func(
      [UserId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'editLesson' : IDL.Func([IDL.Nat, LessonInput], [IDL.Bool], []),
  'editQuizQuestion' : IDL.Func([IDL.Nat, QuizQuestionInput], [IDL.Bool], []),
  'enrollCourse' : IDL.Func([CourseId], [CourseEnrollment], []),
  'generateCertificate' : IDL.Func([EnrollmentId], [Certificate], []),
  'getAdminBookings' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'id' : BookingId,
            'status' : BookingStatus,
            'duration' : IDL.Text,
            'clientName' : IDL.Text,
            'rejectedReason' : IDL.Opt(IDL.Text),
            'userId' : UserId,
            'date' : IDL.Text,
            'createdAt' : Timestamp,
            'clientEmail' : IDL.Text,
            'rescheduledDate' : IDL.Opt(IDL.Text),
            'rescheduledTime' : IDL.Opt(IDL.Text),
            'subService' : IDL.Text,
            'notes' : IDL.Opt(IDL.Text),
            'serviceId' : IDL.Text,
            'location' : LocationType,
            'timeSlot' : TimeSlot,
          })
        ),
      ],
      ['query'],
    ),
  'getAdminCourseBlob' : IDL.Func(
      [CourseId],
      [IDL.Opt(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  'getAdminDashboardData' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalEnrollments' : IDL.Nat,
          'pendingUsers' : IDL.Vec(PublicProfile),
          'totalPayments' : IDL.Nat,
          'totalBookings' : IDL.Nat,
          'analytics' : AnalyticsSummary,
          'recentActivity' : IDL.Vec(ActivityEvent),
          'totalUsers' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getAdminEnrollments' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'id' : EnrollmentId,
            'completedAt' : IDL.Opt(Timestamp),
            'studentEmail' : IDL.Text,
            'paymentStatus' : PaymentStatus__1,
            'studentName' : IDL.Text,
            'userId' : UserId,
            'progress' : IDL.Nat,
            'enrolledAt' : Timestamp,
            'courseName' : IDL.Text,
            'certificateCode' : IDL.Opt(IDL.Text),
            'courseId' : CourseId,
          })
        ),
      ],
      ['query'],
    ),
  'getAdminPaymentDashboard' : IDL.Func(
      [],
      [IDL.Vec(AdminPaymentEntry)],
      ['query'],
    ),
  'getAdminPayments' : IDL.Func([], [IDL.Vec(PaymentOrderExtended)], []),
  'getAdminServiceBlob' : IDL.Func(
      [ServiceId],
      [IDL.Opt(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  'getAdminUsers' : IDL.Func([], [IDL.Vec(PublicProfile)], ['query']),
  'getAllActivityEvents' : IDL.Func([], [IDL.Vec(ActivityEvent)], ['query']),
  'getAllAdminCourses' : IDL.Func([], [IDL.Vec(AdminCourse)], ['query']),
  'getAllAdminServices' : IDL.Func(
      [],
      [IDL.Vec(AdminServiceCategory)],
      ['query'],
    ),
  'getAllBookings' : IDL.Func([], [IDL.Vec(BookingRequest)], ['query']),
  'getAllCmsContent' : IDL.Func([], [IDL.Vec(CmsContent)], ['query']),
  'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getAllEnrollments' : IDL.Func([], [IDL.Vec(CourseEnrollment)], ['query']),
  'getAllFeedback' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
  'getAllPayments' : IDL.Func([], [IDL.Vec(PaymentOrder)], ['query']),
  'getAllSubServiceImages' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getAllUsers' : IDL.Func([], [IDL.Vec(PublicProfile)], ['query']),
  'getAllWorkAssignments' : IDL.Func([], [IDL.Vec(WorkAssignment)], ['query']),
  'getAnalytics' : IDL.Func([], [AnalyticsSummary], ['query']),
  'getBookingsByDate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(BookingRequest)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(PublicProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getCertificate' : IDL.Func([IDL.Text], [IDL.Opt(Certificate)], ['query']),
  'getCmsContent' : IDL.Func([IDL.Text], [IDL.Opt(CmsContent)], ['query']),
  'getCourse' : IDL.Func([CourseId], [IDL.Opt(Course)], ['query']),
  'getCourseProgress' : IDL.Func(
      [CourseId],
      [IDL.Opt(CourseLessonProgress)],
      ['query'],
    ),
  'getCourseProgressByEnrollment' : IDL.Func(
      [EnrollmentId],
      [IDL.Opt(CourseLessonProgress)],
      ['query'],
    ),
  'getEmailLogs' : IDL.Func([], [IDL.Vec(EmailLog)], ['query']),
  'getEnrollmentById' : IDL.Func(
      [EnrollmentId],
      [IDL.Opt(CourseEnrollment)],
      ['query'],
    ),
  'getEnrollmentsByCourse' : IDL.Func(
      [CourseId],
      [
        IDL.Vec(
          IDL.Record({
            'progress' : IDL.Opt(CourseLessonProgress),
            'enrollment' : CourseEnrollment,
          })
        ),
      ],
      ['query'],
    ),
  'getFeedbackForTarget' : IDL.Func([IDL.Text], [IDL.Vec(Feedback)], ['query']),
  'getLessonProgressForCourse' : IDL.Func(
      [CourseId],
      [IDL.Vec(LessonProgress)],
      ['query'],
    ),
  'getLessons' : IDL.Func([CourseId], [IDL.Vec(Lesson)], ['query']),
  'getMediaItems' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(MediaItem)],
      ['query'],
    ),
  'getMyAssignedWork' : IDL.Func([], [IDL.Vec(WorkAssignment)], ['query']),
  'getMyBookings' : IDL.Func([], [IDL.Vec(BookingRequest)], ['query']),
  'getMyCertificate' : IDL.Func(
      [EnrollmentId],
      [IDL.Opt(Certificate)],
      ['query'],
    ),
  'getMyEnrollments' : IDL.Func([], [IDL.Vec(CourseEnrollment)], ['query']),
  'getMyFeedback' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
  'getMyMultiServiceBookings' : IDL.Func(
      [],
      [IDL.Vec(MultiServiceBooking)],
      ['query'],
    ),
  'getMyNotifications' : IDL.Func([], [IDL.Vec(NotificationRecord)], ['query']),
  'getMyPayments' : IDL.Func([], [IDL.Vec(PaymentOrder)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(PublicProfile)], ['query']),
  'getMyUploadedWork' : IDL.Func([], [IDL.Vec(WorkAssignment)], ['query']),
  'getPaymentDetails' : IDL.Func(
      [PaymentId],
      [IDL.Opt(PaymentOrderExtended)],
      ['query'],
    ),
  'getPaymentStatus' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(PaymentVerificationStatus)],
      ['query'],
    ),
  'getPublicCalendar' : IDL.Func([], [IDL.Vec(BookingSlot)], ['query']),
  'getPublicProfile' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PublicProfile)],
      ['query'],
    ),
  'getRecentActivity' : IDL.Func([], [IDL.Vec(ActivityEvent)], ['query']),
  'getServiceCategories' : IDL.Func([], [IDL.Vec(ServiceCategory)], ['query']),
  'getStripeConfig' : IDL.Func(
      [],
      [
        IDL.Record({
          'secretKey' : IDL.Text,
          'configured' : IDL.Bool,
          'publishableKey' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getSubServiceImage' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(IDL.Text)],
      ['query'],
    ),
  'getSubServiceImageBlob' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  'getWhatsAppLogs' : IDL.Func([], [IDL.Vec(WhatsAppLog)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCertificatePaymentDone' : IDL.Func([EnrollmentId], [IDL.Bool], ['query']),
  'listMyPayments' : IDL.Func([], [IDL.Vec(PaymentOrder)], ['query']),
  'listPendingUsers' : IDL.Func([], [IDL.Vec(PublicProfile)], ['query']),
  'loginByEmail' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : PublicProfile, 'err' : LoginError })],
      [],
    ),
  'loginByIdentifier' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : PublicProfile, 'err' : LoginError })],
      [],
    ),
  'manageUser' : IDL.Func([UserId, IDL.Text], [IDL.Bool], []),
  'markCourseComplete' : IDL.Func(
      [EnrollmentId],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'markEnrollmentPaid' : IDL.Func([EnrollmentId], [IDL.Bool], []),
  'markNotificationRead' : IDL.Func([NotificationId], [IDL.Bool], []),
  'markVideoWatched' : IDL.Func([IDL.Nat], [LessonProgress], []),
  'markWorkDelivered' : IDL.Func([BookingId], [IDL.Bool], []),
  'ping' : IDL.Func(
      [],
      [
        IDL.Record({
          'status' : IDL.Text,
          'userCount' : IDL.Nat,
          'bookingCount' : IDL.Nat,
          'enrollmentCount' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'register' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        UserRole,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Vec(IDL.Nat8)),
        IDL.Opt(StudentDetails),
      ],
      [IDL.Variant({ 'ok' : PublicProfile, 'err' : IDL.Text })],
      [],
    ),
  'rejectBooking' : IDL.Func([BookingId, IDL.Text], [IDL.Bool], []),
  'rejectUser' : IDL.Func(
      [UserId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'removeLesson' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'removeQuizQuestion' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'rescheduleBooking' : IDL.Func(
      [BookingId, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'respondToFeedback' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([IDL.Text, IDL.Text, UserRole], [], []),
  'sendBookingConfirmation' : IDL.Func(
      [UserId, BookingDetails],
      [IDL.Bool],
      [],
    ),
  'sendCompletionMessage' : IDL.Func(
      [UserId, BookingDetails, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'sendPaymentReceipt' : IDL.Func(
      [UserId, PaymentReceiptDetails],
      [IDL.Bool],
      [],
    ),
  'sendProgressReminder' : IDL.Func([UserId, BookingDetails], [IDL.Bool], []),
  'setCmsContent' : IDL.Func([IDL.Text, IDL.Text, CmsContentType], [], []),
  'setFeatured' : IDL.Func([MediaId, IDL.Bool], [IDL.Bool], []),
  'setStripeKeys' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'setSubServiceImage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'submitDeliverable' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Bool], []),
  'submitQuiz' : IDL.Func(
      [IDL.Nat, IDL.Vec(IDL.Nat)],
      [IDL.Variant({ 'ok' : QuizResult, 'err' : IDL.Text })],
      [],
    ),
  'testStripeConnection' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'transformWhatsApp' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'triggerPaymentRequest' : IDL.Func([BookingId, IDL.Text], [IDL.Text], []),
  'updateAssignmentStatus' : IDL.Func(
      [IDL.Nat, AssignmentStatus],
      [IDL.Bool],
      [],
    ),
  'updateCourseMode' : IDL.Func([CourseId, CourseMode], [IDL.Bool], []),
  'updateCourseProgress' : IDL.Func([CourseId, IDL.Bool], [IDL.Bool], []),
  'updateProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Bool],
      [],
    ),
  'uploadMedia' : IDL.Func([MediaInput], [MediaItem], []),
  'uploadSubServiceImage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)],
      [],
      [],
    ),
  'verifyCertificate' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const FeedbackTargetType = IDL.Variant({
    'Course' : IDL.Null,
    'Service' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const Feedback = IDL.Record({
    'id' : IDL.Nat,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'responderComment' : IDL.Opt(IDL.Text),
    'comment' : IDL.Text,
    'targetType' : FeedbackTargetType,
    'rating' : IDL.Nat,
    'targetId' : IDL.Text,
  });
  const CourseId = IDL.Nat;
  const LessonInput = IDL.Record({
    'title' : IDL.Text,
    'order' : IDL.Nat,
    'description' : IDL.Text,
    'youtubeUrl' : IDL.Text,
    'courseId' : CourseId,
  });
  const QuizQuestion = IDL.Record({
    'id' : IDL.Nat,
    'lessonId' : IDL.Nat,
    'question' : IDL.Text,
    'correctOptionIndex' : IDL.Nat,
    'options' : IDL.Vec(IDL.Text),
  });
  const Lesson = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'order' : IDL.Nat,
    'description' : IDL.Text,
    'quizQuestions' : IDL.Vec(QuizQuestion),
    'youtubeUrl' : IDL.Text,
    'courseId' : CourseId,
  });
  const QuizQuestionInput = IDL.Record({
    'lessonId' : IDL.Nat,
    'question' : IDL.Text,
    'correctOptionIndex' : IDL.Nat,
    'options' : IDL.Vec(IDL.Text),
  });
  const CourseStatus = IDL.Variant({
    'Inactive' : IDL.Null,
    'Active' : IDL.Null,
    'ComingSoon' : IDL.Null,
  });
  const CourseMode = IDL.Variant({
    'Online' : IDL.Null,
    'Offline' : IDL.Null,
    'Hybrid' : IDL.Null,
  });
  const AdminCourseInput = IDL.Record({
    'status' : CourseStatus,
    'title' : IDL.Text,
    'duration' : IDL.Text,
    'imageData' : IDL.Vec(IDL.Nat8),
    'prerequisites' : IDL.Vec(IDL.Text),
    'mode' : CourseMode,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const AdminCourse = IDL.Record({
    'id' : CourseId,
    'status' : CourseStatus,
    'title' : IDL.Text,
    'duration' : IDL.Text,
    'imageBlob' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'prerequisites' : IDL.Vec(IDL.Text),
    'mode' : CourseMode,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const SubService = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
  const AdminServiceInput = IDL.Record({
    'imageData' : IDL.Vec(IDL.Nat8),
    'subServices' : IDL.Vec(SubService),
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const ServiceId = IDL.Nat;
  const AdminServiceCategory = IDL.Record({
    'id' : ServiceId,
    'imageBlob' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'subServices' : IDL.Vec(SubService),
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
  });
  const PaymentId = IDL.Nat;
  const UserRole = IDL.Variant({
    'Staff' : IDL.Null,
    'Client' : IDL.Null,
    'Student' : IDL.Null,
    'Receptionist' : IDL.Null,
    'Admin' : IDL.Null,
  });
  const StudentDetails = IDL.Record({
    'learningMode' : IDL.Text,
    'preferredSlot' : IDL.Text,
    'courseType' : IDL.Text,
  });
  const UserStatus = IDL.Variant({
    'Active' : IDL.Null,
    'Suspended' : IDL.Null,
    'Rejected' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const PublicProfile = IDL.Record({
    'id' : UserId,
    'status' : UserStatus,
    'name' : IDL.Text,
    'role' : UserRole,
    'studentDetails' : IDL.Opt(StudentDetails),
    'email' : IDL.Text,
    'address' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
    'registeredAt' : Timestamp,
  });
  const CourseLessonProgress = IDL.Record({
    'studentId' : UserId,
    'overallPercent' : IDL.Nat,
    'completedLessonIds' : IDL.Vec(IDL.Nat),
    'certificateEarned' : IDL.Bool,
    'currentLessonId' : IDL.Opt(IDL.Nat),
    'courseId' : CourseId,
  });
  const PaymentStatus = IDL.Variant({
    'Failed' : IDL.Null,
    'Refunded' : IDL.Null,
    'Paid' : IDL.Null,
    'Created' : IDL.Null,
  });
  const PaymentType = IDL.Variant({
    'BookingBalance' : IDL.Null,
    'CertificateDownload' : IDL.Null,
    'CourseEnrollment' : IDL.Null,
    'BookingUpfront' : IDL.Null,
  });
  const PaymentOrder = IDL.Record({
    'id' : PaymentId,
    'signatureVerified' : IDL.Bool,
    'status' : PaymentStatus,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'referenceId' : IDL.Text,
    'orderId' : IDL.Text,
    'currency' : IDL.Text,
    'paymentType' : PaymentType,
    'stripePaymentIntentId' : IDL.Opt(IDL.Text),
    'checkoutUrl' : IDL.Opt(IDL.Text),
    'stripeSessionId' : IDL.Opt(IDL.Text),
    'amount' : IDL.Nat,
    'adminNotes' : IDL.Opt(IDL.Text),
    'verifiedAt' : IDL.Opt(Timestamp),
    'paidAt' : IDL.Opt(Timestamp),
  });
  const PaymentAdminAction = IDL.Variant({
    'confirm' : IDL.Null,
    'adjustAmount' : IDL.Nat,
    'refund' : IDL.Null,
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BookingId = IDL.Nat;
  const WorkAssignmentInput = IDL.Record({
    'bookingId' : BookingId,
    'sessionDate' : IDL.Text,
    'staffId' : UserId,
    'sessionType' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
  });
  const AssignmentStatus = IDL.Variant({
    'Delivered' : IDL.Null,
    'Approved' : IDL.Null,
    'InProgress' : IDL.Null,
    'Assigned' : IDL.Null,
  });
  const Deliverable = IDL.Record({
    'submittedAt' : Timestamp,
    'fileName' : IDL.Text,
    'fileUrl' : IDL.Text,
  });
  const WorkAssignment = IDL.Record({
    'id' : IDL.Nat,
    'status' : AssignmentStatus,
    'bookingId' : BookingId,
    'assignedAt' : Timestamp,
    'sessionDate' : IDL.Text,
    'staffId' : UserId,
    'clientName' : IDL.Text,
    'sessionType' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'deliverables' : IDL.Vec(Deliverable),
  });
  const StripeConfirmation = IDL.Record({
    'stripePaymentIntentId' : IDL.Text,
    'stripeSessionId' : IDL.Text,
  });
  const LocationType = IDL.Variant({
    'Studio' : IDL.Null,
    'Custom' : IDL.Text,
    'Outdoor' : IDL.Null,
    'Indoor' : IDL.Null,
  });
  const TimeSlot = IDL.Variant({
    'Night' : IDL.Null,
    'Afternoon' : IDL.Null,
    'FullDay' : IDL.Null,
    'Morning' : IDL.Null,
    'Evening' : IDL.Null,
    'HalfDay' : IDL.Null,
  });
  const BookingInput = IDL.Record({
    'duration' : IDL.Text,
    'date' : IDL.Text,
    'subService' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'serviceId' : IDL.Text,
    'location' : LocationType,
    'timeSlot' : TimeSlot,
  });
  const BookingStatus = IDL.Variant({
    'WorkDelivered' : IDL.Null,
    'Confirmed' : IDL.Null,
    'Rejected' : IDL.Null,
    'PaymentPending' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Completed' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const BookingRequest = IDL.Record({
    'id' : BookingId,
    'status' : BookingStatus,
    'duration' : IDL.Text,
    'rejectedReason' : IDL.Opt(IDL.Text),
    'userId' : UserId,
    'date' : IDL.Text,
    'createdAt' : Timestamp,
    'rescheduledDate' : IDL.Opt(IDL.Text),
    'rescheduledTime' : IDL.Opt(IDL.Text),
    'subService' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'serviceId' : IDL.Text,
    'location' : LocationType,
    'timeSlot' : TimeSlot,
  });
  const SelectedServiceItem = IDL.Record({
    'name' : IDL.Text,
    'subServiceId' : IDL.Text,
    'serviceId' : IDL.Text,
    'price' : IDL.Nat,
  });
  const MultiServiceBookingInput = IDL.Record({
    'date' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'notes' : IDL.Opt(IDL.Text),
    'selectedServices' : IDL.Vec(SelectedServiceItem),
    'location' : IDL.Text,
    'timeSlot' : IDL.Text,
  });
  const NotificationType = IDL.Variant({
    'BookingCompleted' : IDL.Null,
    'CourseCompleted' : IDL.Null,
    'CourseEnrolled' : IDL.Null,
    'WorkDelivered' : IDL.Null,
    'GeneralInfo' : IDL.Null,
    'PaymentReceipt' : IDL.Null,
    'BookingConfirmed' : IDL.Null,
    'BookingReminder' : IDL.Null,
  });
  const NotificationId = IDL.Nat;
  const NotificationRecord = IDL.Record({
    'id' : NotificationId,
    'userId' : UserId,
    'notificationType' : NotificationType,
    'createdAt' : Timestamp,
    'read' : IDL.Bool,
    'message' : IDL.Text,
  });
  const MediaId = IDL.Nat;
  const EnrollmentId = IDL.Nat;
  const PaymentStatus__1 = IDL.Variant({
    'PartiallyPaid' : IDL.Null,
    'FullyPaid' : IDL.Null,
    'Overdue' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const CourseEnrollment = IDL.Record({
    'id' : EnrollmentId,
    'completedAt' : IDL.Opt(Timestamp),
    'paymentStatus' : PaymentStatus__1,
    'userId' : UserId,
    'progress' : IDL.Nat,
    'enrolledAt' : Timestamp,
    'certificateCode' : IDL.Opt(IDL.Text),
    'courseId' : CourseId,
  });
  const CertificateId = IDL.Nat;
  const Certificate = IDL.Record({
    'id' : CertificateId,
    'verified' : IDL.Bool,
    'enrollmentId' : EnrollmentId,
    'studentName' : IDL.Text,
    'code' : IDL.Text,
    'issuedAt' : Timestamp,
    'courseName' : IDL.Text,
    'courseId' : CourseId,
  });
  const ServiceRevenue = IDL.Record({
    'serviceName' : IDL.Text,
    'revenue' : IDL.Nat,
    'serviceId' : IDL.Text,
    'bookingCount' : IDL.Nat,
  });
  const AnalyticsSummary = IDL.Record({
    'pendingFeedbackCount' : IDL.Nat,
    'pendingBookings' : IDL.Nat,
    'totalEnrollments' : IDL.Nat,
    'emailLogCount' : IDL.Nat,
    'cancelledBookings' : IDL.Nat,
    'totalBookings' : IDL.Nat,
    'totalCourseRevenue' : IDL.Nat,
    'totalMultiServiceBookings' : IDL.Nat,
    'totalFeedback' : IDL.Nat,
    'confirmedBookings' : IDL.Nat,
    'completedBookings' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
    'totalCmsEntries' : IDL.Nat,
    'revenueByService' : IDL.Vec(ServiceRevenue),
  });
  const ActivityEventKind = IDL.Variant({
    'Login' : IDL.Null,
    'Registration' : IDL.Null,
    'Booking' : IDL.Null,
    'Enrollment' : IDL.Null,
    'Payment' : IDL.Null,
  });
  const ActivityEvent = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'userId' : UserId,
    'kind' : ActivityEventKind,
    'detail' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const AdminPaymentEntry = IDL.Record({
    'enrollmentId' : IDL.Opt(EnrollmentId),
    'bookingId' : IDL.Opt(BookingId),
    'clientName' : IDL.Text,
    'order' : PaymentOrder,
    'clientPhone' : IDL.Text,
    'serviceId' : IDL.Opt(IDL.Text),
  });
  const PaymentOrderExtended = IDL.Record({
    'id' : PaymentId,
    'razorpayPaymentId' : IDL.Opt(IDL.Text),
    'status' : IDL.Text,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'referenceId' : IDL.Text,
    'orderId' : IDL.Text,
    'razorpayOrderId' : IDL.Text,
    'currency' : IDL.Text,
    'paymentType' : IDL.Text,
    'selectedServices' : IDL.Vec(SelectedServiceItem),
    'amount' : IDL.Nat,
    'adminNotes' : IDL.Opt(IDL.Text),
    'paidAt' : IDL.Opt(Timestamp),
  });
  const CmsContentType = IDL.Variant({
    'color' : IDL.Null,
    'text' : IDL.Null,
    'imageUrl' : IDL.Null,
  });
  const CmsContent = IDL.Record({
    'key' : IDL.Text,
    'contentType' : CmsContentType,
    'value' : IDL.Text,
    'updatedAt' : Timestamp,
    'updatedBy' : UserId,
  });
  const Course = IDL.Record({
    'id' : CourseId,
    'status' : CourseStatus,
    'title' : IDL.Text,
    'duration' : IDL.Text,
    'prerequisites' : IDL.Vec(IDL.Text),
    'mode' : CourseMode,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const EmailLog = IDL.Record({
    'id' : IDL.Nat,
    'to' : IDL.Text,
    'subject' : IDL.Text,
    'body' : IDL.Text,
    'createdAt' : Timestamp,
    'sent' : IDL.Bool,
    'relatedId' : IDL.Opt(IDL.Text),
  });
  const LessonProgress = IDL.Record({
    'lessonId' : IDL.Nat,
    'completedAt' : IDL.Opt(IDL.Int),
    'studentId' : UserId,
    'quizScore' : IDL.Opt(IDL.Nat),
    'videoWatched' : IDL.Bool,
    'quizPassed' : IDL.Bool,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const FileType = IDL.Variant({ 'Photo' : IDL.Null, 'Video' : IDL.Null });
  const MediaItem = IDL.Record({
    'id' : MediaId,
    'title' : IDL.Text,
    'serviceCategory' : IDL.Text,
    'featured' : IDL.Bool,
    'blob' : ExternalBlob,
    'date' : Timestamp,
    'fileType' : FileType,
    'uploadedBy' : UserId,
  });
  const MultiServiceBooking = IDL.Record({
    'id' : BookingId,
    'status' : IDL.Text,
    'userId' : UserId,
    'date' : IDL.Text,
    'createdAt' : Timestamp,
    'totalAmount' : IDL.Nat,
    'notes' : IDL.Opt(IDL.Text),
    'selectedServices' : IDL.Vec(SelectedServiceItem),
    'adminNotes' : IDL.Opt(IDL.Text),
    'location' : IDL.Text,
    'timeSlot' : IDL.Text,
  });
  const PaymentVerificationStatus = IDL.Record({
    'signatureVerified' : IDL.Bool,
    'status' : PaymentStatus,
    'orderId' : IDL.Text,
    'paymentId' : PaymentId,
    'stripePaymentIntentId' : IDL.Opt(IDL.Text),
    'stripeSessionId' : IDL.Opt(IDL.Text),
    'verifiedAt' : IDL.Opt(Timestamp),
  });
  const SlotStatus = IDL.Variant({
    'Available' : IDL.Null,
    'Taken' : IDL.Null,
  });
  const BookingSlot = IDL.Record({
    'status' : SlotStatus,
    'date' : IDL.Text,
    'timeSlot' : TimeSlot,
  });
  const ServiceCategory = IDL.Record({
    'id' : IDL.Text,
    'subServices' : IDL.Vec(SubService),
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const WhatsAppLog = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : Timestamp,
    'sent' : IDL.Bool,
    'message' : IDL.Text,
    'phone' : IDL.Text,
    'relatedId' : IDL.Opt(IDL.Text),
  });
  const LoginError = IDL.Variant({
    'lockedOut' : IDL.Null,
    'other' : IDL.Text,
    'pendingApproval' : IDL.Null,
    'notFound' : IDL.Null,
    'incorrectPassword' : IDL.Null,
    'suspended' : IDL.Null,
  });
  const BookingDetails = IDL.Record({
    'serviceName' : IDL.Text,
    'bookingId' : IDL.Text,
    'date' : IDL.Text,
    'time' : IDL.Text,
    'clientEmail' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'clientPhone' : IDL.Text,
    'location' : IDL.Text,
  });
  const PaymentReceiptDetails = IDL.Record({
    'clientEmail' : IDL.Text,
    'referenceId' : IDL.Text,
    'currency' : IDL.Text,
    'clientPhone' : IDL.Text,
    'paymentId' : IDL.Text,
    'amount' : IDL.Nat,
    'paidAt' : IDL.Text,
  });
  const QuizResult = IDL.Record({
    'lessonId' : IDL.Nat,
    'score' : IDL.Nat,
    'totalQuestions' : IDL.Nat,
    'passed' : IDL.Bool,
    'courseProgress' : CourseLessonProgress,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const MediaInput = IDL.Record({
    'title' : IDL.Text,
    'serviceCategory' : IDL.Text,
    'blob' : ExternalBlob,
    'fileType' : FileType,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addFeedback' : IDL.Func(
        [IDL.Text, FeedbackTargetType, IDL.Nat, IDL.Text],
        [Feedback],
        [],
      ),
    'addLesson' : IDL.Func([LessonInput], [Lesson], []),
    'addQuizQuestion' : IDL.Func([QuizQuestionInput], [Lesson], []),
    'adminAddCourse' : IDL.Func([AdminCourseInput], [AdminCourse], []),
    'adminAddService' : IDL.Func(
        [AdminServiceInput],
        [AdminServiceCategory],
        [],
      ),
    'adminAdjustAmount' : IDL.Func(
        [PaymentId, IDL.Nat, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'adminConfirmPayment' : IDL.Func([PaymentId, IDL.Text], [IDL.Bool], []),
    'adminCreateUser' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          UserRole,
          IDL.Opt(IDL.Text),
          IDL.Opt(StudentDetails),
        ],
        [IDL.Variant({ 'ok' : PublicProfile, 'err' : IDL.Text })],
        [],
      ),
    'adminDeleteCourse' : IDL.Func([CourseId], [IDL.Bool], []),
    'adminDeleteService' : IDL.Func([ServiceId], [IDL.Bool], []),
    'adminGetAllCourseProgress' : IDL.Func(
        [],
        [IDL.Vec(CourseLessonProgress)],
        ['query'],
      ),
    'adminGetAllPayments' : IDL.Func([], [IDL.Vec(PaymentOrder)], ['query']),
    'adminRefundPayment' : IDL.Func([PaymentId, IDL.Text], [IDL.Bool], []),
    'adminUpdateCourse' : IDL.Func(
        [CourseId, AdminCourseInput],
        [IDL.Bool],
        [],
      ),
    'adminUpdatePayment' : IDL.Func(
        [PaymentId, PaymentAdminAction, IDL.Opt(IDL.Text)],
        [IDL.Bool],
        [],
      ),
    'adminUpdateService' : IDL.Func(
        [ServiceId, AdminServiceInput],
        [IDL.Bool],
        [],
      ),
    'approveUser' : IDL.Func(
        [UserId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'assignWork' : IDL.Func([WorkAssignmentInput], [WorkAssignment], []),
    'bootstrapAdminProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : PublicProfile, 'err' : IDL.Text })],
        [],
      ),
    'bulkGetUserProfiles' : IDL.Func(
        [IDL.Vec(UserId)],
        [IDL.Vec(PublicProfile)],
        ['query'],
      ),
    'clearStaleEnrollments' : IDL.Func([], [IDL.Nat], []),
    'confirmBooking' : IDL.Func([BookingId], [IDL.Bool], []),
    'confirmPayment' : IDL.Func([StripeConfirmation], [IDL.Bool], []),
    'createBookingRequest' : IDL.Func([BookingInput], [BookingRequest], []),
    'createMultiServiceBooking' : IDL.Func(
        [MultiServiceBookingInput],
        [BookingId],
        [],
      ),
    'createPaymentOrder' : IDL.Func(
        [IDL.Nat, IDL.Text, PaymentType],
        [PaymentOrder],
        [],
      ),
    'createSystemNotification' : IDL.Func(
        [UserId, IDL.Text, NotificationType],
        [NotificationRecord],
        [],
      ),
    'deleteCmsContent' : IDL.Func([IDL.Text], [], []),
    'deleteMedia' : IDL.Func([MediaId], [IDL.Bool], []),
    'deleteSubServiceImage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteUser' : IDL.Func(
        [UserId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'editLesson' : IDL.Func([IDL.Nat, LessonInput], [IDL.Bool], []),
    'editQuizQuestion' : IDL.Func([IDL.Nat, QuizQuestionInput], [IDL.Bool], []),
    'enrollCourse' : IDL.Func([CourseId], [CourseEnrollment], []),
    'generateCertificate' : IDL.Func([EnrollmentId], [Certificate], []),
    'getAdminBookings' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'id' : BookingId,
              'status' : BookingStatus,
              'duration' : IDL.Text,
              'clientName' : IDL.Text,
              'rejectedReason' : IDL.Opt(IDL.Text),
              'userId' : UserId,
              'date' : IDL.Text,
              'createdAt' : Timestamp,
              'clientEmail' : IDL.Text,
              'rescheduledDate' : IDL.Opt(IDL.Text),
              'rescheduledTime' : IDL.Opt(IDL.Text),
              'subService' : IDL.Text,
              'notes' : IDL.Opt(IDL.Text),
              'serviceId' : IDL.Text,
              'location' : LocationType,
              'timeSlot' : TimeSlot,
            })
          ),
        ],
        ['query'],
      ),
    'getAdminCourseBlob' : IDL.Func(
        [CourseId],
        [IDL.Opt(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    'getAdminDashboardData' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalEnrollments' : IDL.Nat,
            'pendingUsers' : IDL.Vec(PublicProfile),
            'totalPayments' : IDL.Nat,
            'totalBookings' : IDL.Nat,
            'analytics' : AnalyticsSummary,
            'recentActivity' : IDL.Vec(ActivityEvent),
            'totalUsers' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getAdminEnrollments' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'id' : EnrollmentId,
              'completedAt' : IDL.Opt(Timestamp),
              'studentEmail' : IDL.Text,
              'paymentStatus' : PaymentStatus__1,
              'studentName' : IDL.Text,
              'userId' : UserId,
              'progress' : IDL.Nat,
              'enrolledAt' : Timestamp,
              'courseName' : IDL.Text,
              'certificateCode' : IDL.Opt(IDL.Text),
              'courseId' : CourseId,
            })
          ),
        ],
        ['query'],
      ),
    'getAdminPaymentDashboard' : IDL.Func(
        [],
        [IDL.Vec(AdminPaymentEntry)],
        ['query'],
      ),
    'getAdminPayments' : IDL.Func([], [IDL.Vec(PaymentOrderExtended)], []),
    'getAdminServiceBlob' : IDL.Func(
        [ServiceId],
        [IDL.Opt(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    'getAdminUsers' : IDL.Func([], [IDL.Vec(PublicProfile)], ['query']),
    'getAllActivityEvents' : IDL.Func([], [IDL.Vec(ActivityEvent)], ['query']),
    'getAllAdminCourses' : IDL.Func([], [IDL.Vec(AdminCourse)], ['query']),
    'getAllAdminServices' : IDL.Func(
        [],
        [IDL.Vec(AdminServiceCategory)],
        ['query'],
      ),
    'getAllBookings' : IDL.Func([], [IDL.Vec(BookingRequest)], ['query']),
    'getAllCmsContent' : IDL.Func([], [IDL.Vec(CmsContent)], ['query']),
    'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getAllEnrollments' : IDL.Func([], [IDL.Vec(CourseEnrollment)], ['query']),
    'getAllFeedback' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
    'getAllPayments' : IDL.Func([], [IDL.Vec(PaymentOrder)], ['query']),
    'getAllSubServiceImages' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getAllUsers' : IDL.Func([], [IDL.Vec(PublicProfile)], ['query']),
    'getAllWorkAssignments' : IDL.Func(
        [],
        [IDL.Vec(WorkAssignment)],
        ['query'],
      ),
    'getAnalytics' : IDL.Func([], [AnalyticsSummary], ['query']),
    'getBookingsByDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BookingRequest)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(PublicProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getCertificate' : IDL.Func([IDL.Text], [IDL.Opt(Certificate)], ['query']),
    'getCmsContent' : IDL.Func([IDL.Text], [IDL.Opt(CmsContent)], ['query']),
    'getCourse' : IDL.Func([CourseId], [IDL.Opt(Course)], ['query']),
    'getCourseProgress' : IDL.Func(
        [CourseId],
        [IDL.Opt(CourseLessonProgress)],
        ['query'],
      ),
    'getCourseProgressByEnrollment' : IDL.Func(
        [EnrollmentId],
        [IDL.Opt(CourseLessonProgress)],
        ['query'],
      ),
    'getEmailLogs' : IDL.Func([], [IDL.Vec(EmailLog)], ['query']),
    'getEnrollmentById' : IDL.Func(
        [EnrollmentId],
        [IDL.Opt(CourseEnrollment)],
        ['query'],
      ),
    'getEnrollmentsByCourse' : IDL.Func(
        [CourseId],
        [
          IDL.Vec(
            IDL.Record({
              'progress' : IDL.Opt(CourseLessonProgress),
              'enrollment' : CourseEnrollment,
            })
          ),
        ],
        ['query'],
      ),
    'getFeedbackForTarget' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Feedback)],
        ['query'],
      ),
    'getLessonProgressForCourse' : IDL.Func(
        [CourseId],
        [IDL.Vec(LessonProgress)],
        ['query'],
      ),
    'getLessons' : IDL.Func([CourseId], [IDL.Vec(Lesson)], ['query']),
    'getMediaItems' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(MediaItem)],
        ['query'],
      ),
    'getMyAssignedWork' : IDL.Func([], [IDL.Vec(WorkAssignment)], ['query']),
    'getMyBookings' : IDL.Func([], [IDL.Vec(BookingRequest)], ['query']),
    'getMyCertificate' : IDL.Func(
        [EnrollmentId],
        [IDL.Opt(Certificate)],
        ['query'],
      ),
    'getMyEnrollments' : IDL.Func([], [IDL.Vec(CourseEnrollment)], ['query']),
    'getMyFeedback' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
    'getMyMultiServiceBookings' : IDL.Func(
        [],
        [IDL.Vec(MultiServiceBooking)],
        ['query'],
      ),
    'getMyNotifications' : IDL.Func(
        [],
        [IDL.Vec(NotificationRecord)],
        ['query'],
      ),
    'getMyPayments' : IDL.Func([], [IDL.Vec(PaymentOrder)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(PublicProfile)], ['query']),
    'getMyUploadedWork' : IDL.Func([], [IDL.Vec(WorkAssignment)], ['query']),
    'getPaymentDetails' : IDL.Func(
        [PaymentId],
        [IDL.Opt(PaymentOrderExtended)],
        ['query'],
      ),
    'getPaymentStatus' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(PaymentVerificationStatus)],
        ['query'],
      ),
    'getPublicCalendar' : IDL.Func([], [IDL.Vec(BookingSlot)], ['query']),
    'getPublicProfile' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PublicProfile)],
        ['query'],
      ),
    'getRecentActivity' : IDL.Func([], [IDL.Vec(ActivityEvent)], ['query']),
    'getServiceCategories' : IDL.Func(
        [],
        [IDL.Vec(ServiceCategory)],
        ['query'],
      ),
    'getStripeConfig' : IDL.Func(
        [],
        [
          IDL.Record({
            'secretKey' : IDL.Text,
            'configured' : IDL.Bool,
            'publishableKey' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getSubServiceImage' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getSubServiceImageBlob' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    'getWhatsAppLogs' : IDL.Func([], [IDL.Vec(WhatsAppLog)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCertificatePaymentDone' : IDL.Func(
        [EnrollmentId],
        [IDL.Bool],
        ['query'],
      ),
    'listMyPayments' : IDL.Func([], [IDL.Vec(PaymentOrder)], ['query']),
    'listPendingUsers' : IDL.Func([], [IDL.Vec(PublicProfile)], ['query']),
    'loginByEmail' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : PublicProfile, 'err' : LoginError })],
        [],
      ),
    'loginByIdentifier' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : PublicProfile, 'err' : LoginError })],
        [],
      ),
    'manageUser' : IDL.Func([UserId, IDL.Text], [IDL.Bool], []),
    'markCourseComplete' : IDL.Func(
        [EnrollmentId],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'markEnrollmentPaid' : IDL.Func([EnrollmentId], [IDL.Bool], []),
    'markNotificationRead' : IDL.Func([NotificationId], [IDL.Bool], []),
    'markVideoWatched' : IDL.Func([IDL.Nat], [LessonProgress], []),
    'markWorkDelivered' : IDL.Func([BookingId], [IDL.Bool], []),
    'ping' : IDL.Func(
        [],
        [
          IDL.Record({
            'status' : IDL.Text,
            'userCount' : IDL.Nat,
            'bookingCount' : IDL.Nat,
            'enrollmentCount' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'register' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          UserRole,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Vec(IDL.Nat8)),
          IDL.Opt(StudentDetails),
        ],
        [IDL.Variant({ 'ok' : PublicProfile, 'err' : IDL.Text })],
        [],
      ),
    'rejectBooking' : IDL.Func([BookingId, IDL.Text], [IDL.Bool], []),
    'rejectUser' : IDL.Func(
        [UserId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'removeLesson' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'removeQuizQuestion' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'rescheduleBooking' : IDL.Func(
        [BookingId, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'respondToFeedback' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([IDL.Text, IDL.Text, UserRole], [], []),
    'sendBookingConfirmation' : IDL.Func(
        [UserId, BookingDetails],
        [IDL.Bool],
        [],
      ),
    'sendCompletionMessage' : IDL.Func(
        [UserId, BookingDetails, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'sendPaymentReceipt' : IDL.Func(
        [UserId, PaymentReceiptDetails],
        [IDL.Bool],
        [],
      ),
    'sendProgressReminder' : IDL.Func([UserId, BookingDetails], [IDL.Bool], []),
    'setCmsContent' : IDL.Func([IDL.Text, IDL.Text, CmsContentType], [], []),
    'setFeatured' : IDL.Func([MediaId, IDL.Bool], [IDL.Bool], []),
    'setStripeKeys' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'setSubServiceImage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'submitDeliverable' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'submitQuiz' : IDL.Func(
        [IDL.Nat, IDL.Vec(IDL.Nat)],
        [IDL.Variant({ 'ok' : QuizResult, 'err' : IDL.Text })],
        [],
      ),
    'testStripeConnection' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'transformWhatsApp' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'triggerPaymentRequest' : IDL.Func([BookingId, IDL.Text], [IDL.Text], []),
    'updateAssignmentStatus' : IDL.Func(
        [IDL.Nat, AssignmentStatus],
        [IDL.Bool],
        [],
      ),
    'updateCourseMode' : IDL.Func([CourseId, CourseMode], [IDL.Bool], []),
    'updateCourseProgress' : IDL.Func([CourseId, IDL.Bool], [IDL.Bool], []),
    'updateProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Bool],
        [],
      ),
    'uploadMedia' : IDL.Func([MediaInput], [MediaItem], []),
    'uploadSubServiceImage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)],
        [],
        [],
      ),
    'verifyCertificate' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };