/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const FeedbackTargetType = IDL.Variant({
  'Course' : IDL.Null,
  'Service' : IDL.Null,
});
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const Feedback = IDL.Record({
  'id' : IDL.Nat,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'responderComment' : IDL.Opt(IDL.Text),
  'comment' : IDL.Text,
  'targetType' : FeedbackTargetType,
  'rating' : IDL.Nat,
  'targetId' : IDL.Text,
});
export const PaymentId = IDL.Nat;
export const PaymentAdminAction = IDL.Variant({
  'confirm' : IDL.Null,
  'adjustAmount' : IDL.Nat,
  'refund' : IDL.Null,
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BookingId = IDL.Nat;
export const LocationType = IDL.Variant({
  'Studio' : IDL.Null,
  'Custom' : IDL.Text,
  'Outdoor' : IDL.Null,
  'Indoor' : IDL.Null,
});
export const TimeSlot = IDL.Variant({
  'Night' : IDL.Null,
  'Afternoon' : IDL.Null,
  'FullDay' : IDL.Null,
  'Morning' : IDL.Null,
  'Evening' : IDL.Null,
  'HalfDay' : IDL.Null,
});
export const BookingInput = IDL.Record({
  'duration' : IDL.Text,
  'date' : IDL.Text,
  'subService' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'serviceId' : IDL.Text,
  'location' : LocationType,
  'timeSlot' : TimeSlot,
});
export const BookingStatus = IDL.Variant({
  'WorkDelivered' : IDL.Null,
  'Confirmed' : IDL.Null,
  'PaymentPending' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Completed' : IDL.Null,
  'Pending' : IDL.Null,
});
export const BookingRequest = IDL.Record({
  'id' : BookingId,
  'status' : BookingStatus,
  'duration' : IDL.Text,
  'userId' : UserId,
  'date' : IDL.Text,
  'createdAt' : Timestamp,
  'subService' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'serviceId' : IDL.Text,
  'location' : LocationType,
  'timeSlot' : TimeSlot,
});
export const SelectedServiceItem = IDL.Record({
  'name' : IDL.Text,
  'subServiceId' : IDL.Text,
  'serviceId' : IDL.Text,
  'price' : IDL.Nat,
});
export const MultiServiceBookingInput = IDL.Record({
  'date' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'notes' : IDL.Opt(IDL.Text),
  'selectedServices' : IDL.Vec(SelectedServiceItem),
  'location' : IDL.Text,
  'timeSlot' : IDL.Text,
});
export const PaymentType = IDL.Variant({
  'BookingBalance' : IDL.Null,
  'CourseEnrollment' : IDL.Null,
  'BookingUpfront' : IDL.Null,
});
export const PaymentStatus = IDL.Variant({
  'Failed' : IDL.Null,
  'Refunded' : IDL.Null,
  'Paid' : IDL.Null,
  'Created' : IDL.Null,
});
export const PaymentOrder = IDL.Record({
  'id' : PaymentId,
  'razorpayPaymentId' : IDL.Opt(IDL.Text),
  'signatureVerified' : IDL.Bool,
  'status' : PaymentStatus,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'referenceId' : IDL.Text,
  'orderId' : IDL.Text,
  'razorpayOrderId' : IDL.Text,
  'currency' : IDL.Text,
  'paymentType' : PaymentType,
  'amount' : IDL.Nat,
  'verifiedAt' : IDL.Opt(Timestamp),
  'paidAt' : IDL.Opt(Timestamp),
});
export const NotificationType = IDL.Variant({
  'CourseEnrolled' : IDL.Null,
  'WorkDelivered' : IDL.Null,
  'GeneralInfo' : IDL.Null,
  'BookingConfirmed' : IDL.Null,
  'PaymentRequired' : IDL.Null,
});
export const NotificationId = IDL.Nat;
export const NotificationRecord = IDL.Record({
  'id' : NotificationId,
  'userId' : UserId,
  'notificationType' : NotificationType,
  'createdAt' : Timestamp,
  'read' : IDL.Bool,
  'message' : IDL.Text,
});
export const MediaId = IDL.Nat;
export const CourseId = IDL.Nat;
export const EnrollmentId = IDL.Nat;
export const PaymentStatus__1 = IDL.Variant({
  'PartiallyPaid' : IDL.Null,
  'FullyPaid' : IDL.Null,
  'Overdue' : IDL.Null,
  'Pending' : IDL.Null,
});
export const CourseEnrollment = IDL.Record({
  'id' : EnrollmentId,
  'completedAt' : IDL.Opt(Timestamp),
  'paymentStatus' : PaymentStatus__1,
  'userId' : UserId,
  'progress' : IDL.Nat,
  'enrolledAt' : Timestamp,
  'certificateCode' : IDL.Opt(IDL.Text),
  'courseId' : CourseId,
});
export const CertificateId = IDL.Nat;
export const Certificate = IDL.Record({
  'id' : CertificateId,
  'verified' : IDL.Bool,
  'enrollmentId' : EnrollmentId,
  'studentName' : IDL.Text,
  'code' : IDL.Text,
  'issuedAt' : Timestamp,
  'courseName' : IDL.Text,
  'courseId' : CourseId,
});
export const PaymentOrderExtended = IDL.Record({
  'id' : PaymentId,
  'razorpayPaymentId' : IDL.Opt(IDL.Text),
  'status' : IDL.Text,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'referenceId' : IDL.Text,
  'orderId' : IDL.Text,
  'razorpayOrderId' : IDL.Text,
  'currency' : IDL.Text,
  'paymentType' : IDL.Text,
  'selectedServices' : IDL.Vec(SelectedServiceItem),
  'amount' : IDL.Nat,
  'adminNotes' : IDL.Opt(IDL.Text),
  'paidAt' : IDL.Opt(Timestamp),
});
export const CmsContentType = IDL.Variant({
  'color' : IDL.Null,
  'text' : IDL.Null,
  'imageUrl' : IDL.Null,
});
export const CmsContent = IDL.Record({
  'key' : IDL.Text,
  'contentType' : CmsContentType,
  'value' : IDL.Text,
  'updatedAt' : Timestamp,
  'updatedBy' : UserId,
});
export const CourseStatus = IDL.Variant({
  'Inactive' : IDL.Null,
  'Active' : IDL.Null,
  'ComingSoon' : IDL.Null,
});
export const CourseMode = IDL.Variant({
  'Online' : IDL.Null,
  'Offline' : IDL.Null,
  'Hybrid' : IDL.Null,
});
export const Course = IDL.Record({
  'id' : CourseId,
  'status' : CourseStatus,
  'title' : IDL.Text,
  'duration' : IDL.Text,
  'prerequisites' : IDL.Vec(IDL.Text),
  'mode' : CourseMode,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const UserStatus = IDL.Variant({
  'Active' : IDL.Null,
  'Suspended' : IDL.Null,
  'Pending' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'Staff' : IDL.Null,
  'Client' : IDL.Null,
  'Student' : IDL.Null,
  'Receptionist' : IDL.Null,
  'Admin' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'status' : UserStatus,
  'created' : Timestamp,
  'principal' : UserId,
  'name' : IDL.Text,
  'role' : UserRole,
  'email' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
});
export const ServiceRevenue = IDL.Record({
  'serviceName' : IDL.Text,
  'revenue' : IDL.Nat,
  'serviceId' : IDL.Text,
  'bookingCount' : IDL.Nat,
});
export const BookingStats = IDL.Record({
  'pendingFeedbackCount' : IDL.Nat,
  'pendingBookings' : IDL.Nat,
  'totalEnrollments' : IDL.Nat,
  'emailLogCount' : IDL.Nat,
  'cancelledBookings' : IDL.Nat,
  'totalBookings' : IDL.Nat,
  'totalCourseRevenue' : IDL.Nat,
  'totalMultiServiceBookings' : IDL.Nat,
  'totalFeedback' : IDL.Nat,
  'confirmedBookings' : IDL.Nat,
  'completedBookings' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
  'totalCmsEntries' : IDL.Nat,
  'revenueByService' : IDL.Vec(ServiceRevenue),
});
export const EmailLog = IDL.Record({
  'id' : IDL.Nat,
  'to' : IDL.Text,
  'subject' : IDL.Text,
  'body' : IDL.Text,
  'createdAt' : Timestamp,
  'relatedId' : IDL.Opt(IDL.Text),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const FileType = IDL.Variant({ 'Photo' : IDL.Null, 'Video' : IDL.Null });
export const MediaItem = IDL.Record({
  'id' : MediaId,
  'title' : IDL.Text,
  'serviceCategory' : IDL.Text,
  'featured' : IDL.Bool,
  'blob' : ExternalBlob,
  'date' : Timestamp,
  'fileType' : FileType,
  'uploadedBy' : UserId,
});
export const MultiServiceBooking = IDL.Record({
  'id' : BookingId,
  'status' : IDL.Text,
  'userId' : UserId,
  'date' : IDL.Text,
  'createdAt' : Timestamp,
  'totalAmount' : IDL.Nat,
  'notes' : IDL.Opt(IDL.Text),
  'selectedServices' : IDL.Vec(SelectedServiceItem),
  'adminNotes' : IDL.Opt(IDL.Text),
  'location' : IDL.Text,
  'timeSlot' : IDL.Text,
});
export const PaymentVerificationStatus = IDL.Record({
  'razorpayPaymentId' : IDL.Opt(IDL.Text),
  'signatureVerified' : IDL.Bool,
  'status' : PaymentStatus,
  'orderId' : IDL.Text,
  'razorpayOrderId' : IDL.Text,
  'paymentId' : PaymentId,
  'verifiedAt' : IDL.Opt(Timestamp),
});
export const SlotStatus = IDL.Variant({
  'Available' : IDL.Null,
  'Taken' : IDL.Null,
});
export const BookingSlot = IDL.Record({
  'status' : SlotStatus,
  'date' : IDL.Text,
  'timeSlot' : TimeSlot,
});
export const SubService = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
export const ServiceCategory = IDL.Record({
  'id' : IDL.Text,
  'subServices' : IDL.Vec(SubService),
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const MediaInput = IDL.Record({
  'title' : IDL.Text,
  'serviceCategory' : IDL.Text,
  'blob' : ExternalBlob,
  'fileType' : FileType,
});
export const PaymentVerification = IDL.Record({
  'razorpayPaymentId' : IDL.Text,
  'razorpaySignature' : IDL.Text,
  'razorpayOrderId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addFeedback' : IDL.Func(
      [IDL.Text, FeedbackTargetType, IDL.Nat, IDL.Text],
      [Feedback],
      [],
    ),
  'adminUpdatePayment' : IDL.Func(
      [PaymentId, PaymentAdminAction, IDL.Opt(IDL.Text)],
      [IDL.Bool],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'confirmBooking' : IDL.Func([BookingId], [IDL.Bool], []),
  'createBookingRequest' : IDL.Func([BookingInput], [BookingRequest], []),
  'createMultiServiceBooking' : IDL.Func(
      [MultiServiceBookingInput],
      [BookingId],
      [],
    ),
  'createPaymentOrder' : IDL.Func(
      [IDL.Nat, IDL.Text, PaymentType],
      [PaymentOrder],
      [],
    ),
  'createSystemNotification' : IDL.Func(
      [UserId, IDL.Text, NotificationType],
      [NotificationRecord],
      [],
    ),
  'deleteCmsContent' : IDL.Func([IDL.Text], [], []),
  'deleteMedia' : IDL.Func([MediaId], [IDL.Bool], []),
  'deleteSubServiceImage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'enrollCourse' : IDL.Func([CourseId], [CourseEnrollment], []),
  'generateCertificate' : IDL.Func([EnrollmentId], [Certificate], []),
  'getAdminPayments' : IDL.Func([], [IDL.Vec(PaymentOrderExtended)], []),
  'getAllBookings' : IDL.Func([], [IDL.Vec(BookingRequest)], ['query']),
  'getAllCmsContent' : IDL.Func([], [IDL.Vec(CmsContent)], ['query']),
  'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getAllEnrollments' : IDL.Func([], [IDL.Vec(CourseEnrollment)], ['query']),
  'getAllFeedback' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
  'getAllPayments' : IDL.Func([], [IDL.Vec(PaymentOrder)], ['query']),
  'getAllSubServiceImages' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAnalytics' : IDL.Func([], [BookingStats], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getCertificate' : IDL.Func([IDL.Text], [IDL.Opt(Certificate)], ['query']),
  'getCmsContent' : IDL.Func([IDL.Text], [IDL.Opt(CmsContent)], ['query']),
  'getCourse' : IDL.Func([CourseId], [IDL.Opt(Course)], ['query']),
  'getEmailLogs' : IDL.Func([], [IDL.Vec(EmailLog)], ['query']),
  'getFeedbackForTarget' : IDL.Func([IDL.Text], [IDL.Vec(Feedback)], ['query']),
  'getMediaItems' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(MediaItem)],
      ['query'],
    ),
  'getMyBookings' : IDL.Func([], [IDL.Vec(BookingRequest)], ['query']),
  'getMyEnrollments' : IDL.Func([], [IDL.Vec(CourseEnrollment)], ['query']),
  'getMyFeedback' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
  'getMyMultiServiceBookings' : IDL.Func(
      [],
      [IDL.Vec(MultiServiceBooking)],
      ['query'],
    ),
  'getMyNotifications' : IDL.Func([], [IDL.Vec(NotificationRecord)], ['query']),
  'getMyPayments' : IDL.Func([], [IDL.Vec(PaymentOrder)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getPaymentDetails' : IDL.Func(
      [PaymentId],
      [IDL.Opt(PaymentOrderExtended)],
      ['query'],
    ),
  'getPaymentVerificationStatus' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(PaymentVerificationStatus)],
      ['query'],
    ),
  'getPublicCalendar' : IDL.Func([], [IDL.Vec(BookingSlot)], ['query']),
  'getServiceCategories' : IDL.Func([], [IDL.Vec(ServiceCategory)], ['query']),
  'getSubServiceImage' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(IDL.Text)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logBookingConfirmedEmail' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [EmailLog],
      [],
    ),
  'logEnrollmentConfirmedEmail' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [EmailLog],
      [],
    ),
  'manageUser' : IDL.Func([UserId, IDL.Text], [IDL.Bool], []),
  'markEnrollmentPaid' : IDL.Func([EnrollmentId], [IDL.Bool], []),
  'markNotificationRead' : IDL.Func([NotificationId], [IDL.Bool], []),
  'markWorkDelivered' : IDL.Func([BookingId], [IDL.Bool], []),
  'register' : IDL.Func([IDL.Text, IDL.Text, UserRole], [UserProfile], []),
  'respondToFeedback' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([IDL.Text, IDL.Text, UserRole], [], []),
  'sendWhatsAppNotification' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'setCmsContent' : IDL.Func([IDL.Text, IDL.Text, CmsContentType], [], []),
  'setFeatured' : IDL.Func([MediaId, IDL.Bool], [IDL.Bool], []),
  'setSubServiceImage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'triggerPaymentRequest' : IDL.Func([BookingId, IDL.Text], [IDL.Text], []),
  'updateCourseProgress' : IDL.Func([CourseId, IDL.Bool], [IDL.Bool], []),
  'updateProfile' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'uploadMedia' : IDL.Func([MediaInput], [MediaItem], []),
  'verifyCertificate' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'verifyPayment' : IDL.Func([PaymentVerification], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const FeedbackTargetType = IDL.Variant({
    'Course' : IDL.Null,
    'Service' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const Feedback = IDL.Record({
    'id' : IDL.Nat,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'responderComment' : IDL.Opt(IDL.Text),
    'comment' : IDL.Text,
    'targetType' : FeedbackTargetType,
    'rating' : IDL.Nat,
    'targetId' : IDL.Text,
  });
  const PaymentId = IDL.Nat;
  const PaymentAdminAction = IDL.Variant({
    'confirm' : IDL.Null,
    'adjustAmount' : IDL.Nat,
    'refund' : IDL.Null,
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BookingId = IDL.Nat;
  const LocationType = IDL.Variant({
    'Studio' : IDL.Null,
    'Custom' : IDL.Text,
    'Outdoor' : IDL.Null,
    'Indoor' : IDL.Null,
  });
  const TimeSlot = IDL.Variant({
    'Night' : IDL.Null,
    'Afternoon' : IDL.Null,
    'FullDay' : IDL.Null,
    'Morning' : IDL.Null,
    'Evening' : IDL.Null,
    'HalfDay' : IDL.Null,
  });
  const BookingInput = IDL.Record({
    'duration' : IDL.Text,
    'date' : IDL.Text,
    'subService' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'serviceId' : IDL.Text,
    'location' : LocationType,
    'timeSlot' : TimeSlot,
  });
  const BookingStatus = IDL.Variant({
    'WorkDelivered' : IDL.Null,
    'Confirmed' : IDL.Null,
    'PaymentPending' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Completed' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const BookingRequest = IDL.Record({
    'id' : BookingId,
    'status' : BookingStatus,
    'duration' : IDL.Text,
    'userId' : UserId,
    'date' : IDL.Text,
    'createdAt' : Timestamp,
    'subService' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'serviceId' : IDL.Text,
    'location' : LocationType,
    'timeSlot' : TimeSlot,
  });
  const SelectedServiceItem = IDL.Record({
    'name' : IDL.Text,
    'subServiceId' : IDL.Text,
    'serviceId' : IDL.Text,
    'price' : IDL.Nat,
  });
  const MultiServiceBookingInput = IDL.Record({
    'date' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'notes' : IDL.Opt(IDL.Text),
    'selectedServices' : IDL.Vec(SelectedServiceItem),
    'location' : IDL.Text,
    'timeSlot' : IDL.Text,
  });
  const PaymentType = IDL.Variant({
    'BookingBalance' : IDL.Null,
    'CourseEnrollment' : IDL.Null,
    'BookingUpfront' : IDL.Null,
  });
  const PaymentStatus = IDL.Variant({
    'Failed' : IDL.Null,
    'Refunded' : IDL.Null,
    'Paid' : IDL.Null,
    'Created' : IDL.Null,
  });
  const PaymentOrder = IDL.Record({
    'id' : PaymentId,
    'razorpayPaymentId' : IDL.Opt(IDL.Text),
    'signatureVerified' : IDL.Bool,
    'status' : PaymentStatus,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'referenceId' : IDL.Text,
    'orderId' : IDL.Text,
    'razorpayOrderId' : IDL.Text,
    'currency' : IDL.Text,
    'paymentType' : PaymentType,
    'amount' : IDL.Nat,
    'verifiedAt' : IDL.Opt(Timestamp),
    'paidAt' : IDL.Opt(Timestamp),
  });
  const NotificationType = IDL.Variant({
    'CourseEnrolled' : IDL.Null,
    'WorkDelivered' : IDL.Null,
    'GeneralInfo' : IDL.Null,
    'BookingConfirmed' : IDL.Null,
    'PaymentRequired' : IDL.Null,
  });
  const NotificationId = IDL.Nat;
  const NotificationRecord = IDL.Record({
    'id' : NotificationId,
    'userId' : UserId,
    'notificationType' : NotificationType,
    'createdAt' : Timestamp,
    'read' : IDL.Bool,
    'message' : IDL.Text,
  });
  const MediaId = IDL.Nat;
  const CourseId = IDL.Nat;
  const EnrollmentId = IDL.Nat;
  const PaymentStatus__1 = IDL.Variant({
    'PartiallyPaid' : IDL.Null,
    'FullyPaid' : IDL.Null,
    'Overdue' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const CourseEnrollment = IDL.Record({
    'id' : EnrollmentId,
    'completedAt' : IDL.Opt(Timestamp),
    'paymentStatus' : PaymentStatus__1,
    'userId' : UserId,
    'progress' : IDL.Nat,
    'enrolledAt' : Timestamp,
    'certificateCode' : IDL.Opt(IDL.Text),
    'courseId' : CourseId,
  });
  const CertificateId = IDL.Nat;
  const Certificate = IDL.Record({
    'id' : CertificateId,
    'verified' : IDL.Bool,
    'enrollmentId' : EnrollmentId,
    'studentName' : IDL.Text,
    'code' : IDL.Text,
    'issuedAt' : Timestamp,
    'courseName' : IDL.Text,
    'courseId' : CourseId,
  });
  const PaymentOrderExtended = IDL.Record({
    'id' : PaymentId,
    'razorpayPaymentId' : IDL.Opt(IDL.Text),
    'status' : IDL.Text,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'referenceId' : IDL.Text,
    'orderId' : IDL.Text,
    'razorpayOrderId' : IDL.Text,
    'currency' : IDL.Text,
    'paymentType' : IDL.Text,
    'selectedServices' : IDL.Vec(SelectedServiceItem),
    'amount' : IDL.Nat,
    'adminNotes' : IDL.Opt(IDL.Text),
    'paidAt' : IDL.Opt(Timestamp),
  });
  const CmsContentType = IDL.Variant({
    'color' : IDL.Null,
    'text' : IDL.Null,
    'imageUrl' : IDL.Null,
  });
  const CmsContent = IDL.Record({
    'key' : IDL.Text,
    'contentType' : CmsContentType,
    'value' : IDL.Text,
    'updatedAt' : Timestamp,
    'updatedBy' : UserId,
  });
  const CourseStatus = IDL.Variant({
    'Inactive' : IDL.Null,
    'Active' : IDL.Null,
    'ComingSoon' : IDL.Null,
  });
  const CourseMode = IDL.Variant({
    'Online' : IDL.Null,
    'Offline' : IDL.Null,
    'Hybrid' : IDL.Null,
  });
  const Course = IDL.Record({
    'id' : CourseId,
    'status' : CourseStatus,
    'title' : IDL.Text,
    'duration' : IDL.Text,
    'prerequisites' : IDL.Vec(IDL.Text),
    'mode' : CourseMode,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const UserStatus = IDL.Variant({
    'Active' : IDL.Null,
    'Suspended' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'Staff' : IDL.Null,
    'Client' : IDL.Null,
    'Student' : IDL.Null,
    'Receptionist' : IDL.Null,
    'Admin' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'status' : UserStatus,
    'created' : Timestamp,
    'principal' : UserId,
    'name' : IDL.Text,
    'role' : UserRole,
    'email' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
  });
  const ServiceRevenue = IDL.Record({
    'serviceName' : IDL.Text,
    'revenue' : IDL.Nat,
    'serviceId' : IDL.Text,
    'bookingCount' : IDL.Nat,
  });
  const BookingStats = IDL.Record({
    'pendingFeedbackCount' : IDL.Nat,
    'pendingBookings' : IDL.Nat,
    'totalEnrollments' : IDL.Nat,
    'emailLogCount' : IDL.Nat,
    'cancelledBookings' : IDL.Nat,
    'totalBookings' : IDL.Nat,
    'totalCourseRevenue' : IDL.Nat,
    'totalMultiServiceBookings' : IDL.Nat,
    'totalFeedback' : IDL.Nat,
    'confirmedBookings' : IDL.Nat,
    'completedBookings' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
    'totalCmsEntries' : IDL.Nat,
    'revenueByService' : IDL.Vec(ServiceRevenue),
  });
  const EmailLog = IDL.Record({
    'id' : IDL.Nat,
    'to' : IDL.Text,
    'subject' : IDL.Text,
    'body' : IDL.Text,
    'createdAt' : Timestamp,
    'relatedId' : IDL.Opt(IDL.Text),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const FileType = IDL.Variant({ 'Photo' : IDL.Null, 'Video' : IDL.Null });
  const MediaItem = IDL.Record({
    'id' : MediaId,
    'title' : IDL.Text,
    'serviceCategory' : IDL.Text,
    'featured' : IDL.Bool,
    'blob' : ExternalBlob,
    'date' : Timestamp,
    'fileType' : FileType,
    'uploadedBy' : UserId,
  });
  const MultiServiceBooking = IDL.Record({
    'id' : BookingId,
    'status' : IDL.Text,
    'userId' : UserId,
    'date' : IDL.Text,
    'createdAt' : Timestamp,
    'totalAmount' : IDL.Nat,
    'notes' : IDL.Opt(IDL.Text),
    'selectedServices' : IDL.Vec(SelectedServiceItem),
    'adminNotes' : IDL.Opt(IDL.Text),
    'location' : IDL.Text,
    'timeSlot' : IDL.Text,
  });
  const PaymentVerificationStatus = IDL.Record({
    'razorpayPaymentId' : IDL.Opt(IDL.Text),
    'signatureVerified' : IDL.Bool,
    'status' : PaymentStatus,
    'orderId' : IDL.Text,
    'razorpayOrderId' : IDL.Text,
    'paymentId' : PaymentId,
    'verifiedAt' : IDL.Opt(Timestamp),
  });
  const SlotStatus = IDL.Variant({
    'Available' : IDL.Null,
    'Taken' : IDL.Null,
  });
  const BookingSlot = IDL.Record({
    'status' : SlotStatus,
    'date' : IDL.Text,
    'timeSlot' : TimeSlot,
  });
  const SubService = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
  const ServiceCategory = IDL.Record({
    'id' : IDL.Text,
    'subServices' : IDL.Vec(SubService),
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const MediaInput = IDL.Record({
    'title' : IDL.Text,
    'serviceCategory' : IDL.Text,
    'blob' : ExternalBlob,
    'fileType' : FileType,
  });
  const PaymentVerification = IDL.Record({
    'razorpayPaymentId' : IDL.Text,
    'razorpaySignature' : IDL.Text,
    'razorpayOrderId' : IDL.Text,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addFeedback' : IDL.Func(
        [IDL.Text, FeedbackTargetType, IDL.Nat, IDL.Text],
        [Feedback],
        [],
      ),
    'adminUpdatePayment' : IDL.Func(
        [PaymentId, PaymentAdminAction, IDL.Opt(IDL.Text)],
        [IDL.Bool],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'confirmBooking' : IDL.Func([BookingId], [IDL.Bool], []),
    'createBookingRequest' : IDL.Func([BookingInput], [BookingRequest], []),
    'createMultiServiceBooking' : IDL.Func(
        [MultiServiceBookingInput],
        [BookingId],
        [],
      ),
    'createPaymentOrder' : IDL.Func(
        [IDL.Nat, IDL.Text, PaymentType],
        [PaymentOrder],
        [],
      ),
    'createSystemNotification' : IDL.Func(
        [UserId, IDL.Text, NotificationType],
        [NotificationRecord],
        [],
      ),
    'deleteCmsContent' : IDL.Func([IDL.Text], [], []),
    'deleteMedia' : IDL.Func([MediaId], [IDL.Bool], []),
    'deleteSubServiceImage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'enrollCourse' : IDL.Func([CourseId], [CourseEnrollment], []),
    'generateCertificate' : IDL.Func([EnrollmentId], [Certificate], []),
    'getAdminPayments' : IDL.Func([], [IDL.Vec(PaymentOrderExtended)], []),
    'getAllBookings' : IDL.Func([], [IDL.Vec(BookingRequest)], ['query']),
    'getAllCmsContent' : IDL.Func([], [IDL.Vec(CmsContent)], ['query']),
    'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getAllEnrollments' : IDL.Func([], [IDL.Vec(CourseEnrollment)], ['query']),
    'getAllFeedback' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
    'getAllPayments' : IDL.Func([], [IDL.Vec(PaymentOrder)], ['query']),
    'getAllSubServiceImages' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAnalytics' : IDL.Func([], [BookingStats], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getCertificate' : IDL.Func([IDL.Text], [IDL.Opt(Certificate)], ['query']),
    'getCmsContent' : IDL.Func([IDL.Text], [IDL.Opt(CmsContent)], ['query']),
    'getCourse' : IDL.Func([CourseId], [IDL.Opt(Course)], ['query']),
    'getEmailLogs' : IDL.Func([], [IDL.Vec(EmailLog)], ['query']),
    'getFeedbackForTarget' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Feedback)],
        ['query'],
      ),
    'getMediaItems' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(MediaItem)],
        ['query'],
      ),
    'getMyBookings' : IDL.Func([], [IDL.Vec(BookingRequest)], ['query']),
    'getMyEnrollments' : IDL.Func([], [IDL.Vec(CourseEnrollment)], ['query']),
    'getMyFeedback' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
    'getMyMultiServiceBookings' : IDL.Func(
        [],
        [IDL.Vec(MultiServiceBooking)],
        ['query'],
      ),
    'getMyNotifications' : IDL.Func(
        [],
        [IDL.Vec(NotificationRecord)],
        ['query'],
      ),
    'getMyPayments' : IDL.Func([], [IDL.Vec(PaymentOrder)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getPaymentDetails' : IDL.Func(
        [PaymentId],
        [IDL.Opt(PaymentOrderExtended)],
        ['query'],
      ),
    'getPaymentVerificationStatus' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(PaymentVerificationStatus)],
        ['query'],
      ),
    'getPublicCalendar' : IDL.Func([], [IDL.Vec(BookingSlot)], ['query']),
    'getServiceCategories' : IDL.Func(
        [],
        [IDL.Vec(ServiceCategory)],
        ['query'],
      ),
    'getSubServiceImage' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logBookingConfirmedEmail' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [EmailLog],
        [],
      ),
    'logEnrollmentConfirmedEmail' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [EmailLog],
        [],
      ),
    'manageUser' : IDL.Func([UserId, IDL.Text], [IDL.Bool], []),
    'markEnrollmentPaid' : IDL.Func([EnrollmentId], [IDL.Bool], []),
    'markNotificationRead' : IDL.Func([NotificationId], [IDL.Bool], []),
    'markWorkDelivered' : IDL.Func([BookingId], [IDL.Bool], []),
    'register' : IDL.Func([IDL.Text, IDL.Text, UserRole], [UserProfile], []),
    'respondToFeedback' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([IDL.Text, IDL.Text, UserRole], [], []),
    'sendWhatsAppNotification' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'setCmsContent' : IDL.Func([IDL.Text, IDL.Text, CmsContentType], [], []),
    'setFeatured' : IDL.Func([MediaId, IDL.Bool], [IDL.Bool], []),
    'setSubServiceImage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'triggerPaymentRequest' : IDL.Func([BookingId, IDL.Text], [IDL.Text], []),
    'updateCourseProgress' : IDL.Func([CourseId, IDL.Bool], [IDL.Bool], []),
    'updateProfile' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'uploadMedia' : IDL.Func([MediaInput], [MediaItem], []),
    'verifyCertificate' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'verifyPayment' : IDL.Func([PaymentVerification], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };