/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminPaymentEntry {
  'enrollmentId' : [] | [EnrollmentId],
  'bookingId' : [] | [BookingId],
  'clientName' : string,
  'order' : PaymentOrder,
  'clientPhone' : string,
  'serviceId' : [] | [string],
}
export interface BookingDetails {
  'serviceName' : string,
  'bookingId' : string,
  'date' : string,
  'time' : string,
  'clientEmail' : string,
  'totalAmount' : bigint,
  'clientPhone' : string,
  'location' : string,
}
export type BookingId = bigint;
export interface BookingInput {
  'duration' : string,
  'date' : string,
  'subService' : string,
  'notes' : [] | [string],
  'serviceId' : string,
  'location' : LocationType,
  'timeSlot' : TimeSlot,
}
export interface BookingRequest {
  'id' : BookingId,
  'status' : BookingStatus,
  'duration' : string,
  'userId' : UserId,
  'date' : string,
  'createdAt' : Timestamp,
  'subService' : string,
  'notes' : [] | [string],
  'serviceId' : string,
  'location' : LocationType,
  'timeSlot' : TimeSlot,
}
export interface BookingSlot {
  'status' : SlotStatus,
  'date' : string,
  'timeSlot' : TimeSlot,
}
export interface BookingStats {
  'pendingFeedbackCount' : bigint,
  'pendingBookings' : bigint,
  'totalEnrollments' : bigint,
  'emailLogCount' : bigint,
  'cancelledBookings' : bigint,
  'totalBookings' : bigint,
  'totalCourseRevenue' : bigint,
  'totalMultiServiceBookings' : bigint,
  'totalFeedback' : bigint,
  'confirmedBookings' : bigint,
  'completedBookings' : bigint,
  'totalRevenue' : bigint,
  'totalCmsEntries' : bigint,
  'revenueByService' : Array<ServiceRevenue>,
}
export type BookingStatus = { 'WorkDelivered' : null } |
  { 'Confirmed' : null } |
  { 'PaymentPending' : null } |
  { 'Cancelled' : null } |
  { 'Completed' : null } |
  { 'Pending' : null };
export interface Certificate {
  'id' : CertificateId,
  'verified' : boolean,
  'enrollmentId' : EnrollmentId,
  'studentName' : string,
  'code' : string,
  'issuedAt' : Timestamp,
  'courseName' : string,
  'courseId' : CourseId,
}
export type CertificateId = bigint;
export interface CmsContent {
  'key' : string,
  'contentType' : CmsContentType,
  'value' : string,
  'updatedAt' : Timestamp,
  'updatedBy' : UserId,
}
export type CmsContentType = { 'color' : null } |
  { 'text' : null } |
  { 'imageUrl' : null };
export interface Course {
  'id' : CourseId,
  'status' : CourseStatus,
  'title' : string,
  'duration' : string,
  'prerequisites' : Array<string>,
  'mode' : CourseMode,
  'description' : string,
  'imageUrl' : string,
  'category' : string,
  'price' : bigint,
}
export interface CourseEnrollment {
  'id' : EnrollmentId,
  'completedAt' : [] | [Timestamp],
  'paymentStatus' : PaymentStatus__1,
  'userId' : UserId,
  'progress' : bigint,
  'enrolledAt' : Timestamp,
  'certificateCode' : [] | [string],
  'courseId' : CourseId,
}
export type CourseId = bigint;
export type CourseMode = { 'Online' : null } |
  { 'Offline' : null } |
  { 'Hybrid' : null };
export type CourseStatus = { 'Inactive' : null } |
  { 'Active' : null } |
  { 'ComingSoon' : null };
export interface EmailLog {
  'id' : bigint,
  'to' : string,
  'subject' : string,
  'body' : string,
  'createdAt' : Timestamp,
  'sent' : boolean,
  'relatedId' : [] | [string],
}
export type EnrollmentId = bigint;
export type ExternalBlob = Uint8Array;
export interface Feedback {
  'id' : bigint,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'responderComment' : [] | [string],
  'comment' : string,
  'targetType' : FeedbackTargetType,
  'rating' : bigint,
  'targetId' : string,
}
export type FeedbackTargetType = { 'Course' : null } |
  { 'Service' : null };
export type FileType = { 'Photo' : null } |
  { 'Video' : null };
export type LocationType = { 'Studio' : null } |
  { 'Custom' : string } |
  { 'Outdoor' : null } |
  { 'Indoor' : null };
export type MediaId = bigint;
export interface MediaInput {
  'title' : string,
  'serviceCategory' : string,
  'blob' : ExternalBlob,
  'fileType' : FileType,
}
export interface MediaItem {
  'id' : MediaId,
  'title' : string,
  'serviceCategory' : string,
  'featured' : boolean,
  'blob' : ExternalBlob,
  'date' : Timestamp,
  'fileType' : FileType,
  'uploadedBy' : UserId,
}
export interface MultiServiceBooking {
  'id' : BookingId,
  'status' : string,
  'userId' : UserId,
  'date' : string,
  'createdAt' : Timestamp,
  'totalAmount' : bigint,
  'notes' : [] | [string],
  'selectedServices' : Array<SelectedServiceItem>,
  'adminNotes' : [] | [string],
  'location' : string,
  'timeSlot' : string,
}
export interface MultiServiceBookingInput {
  'date' : string,
  'totalAmount' : bigint,
  'notes' : [] | [string],
  'selectedServices' : Array<SelectedServiceItem>,
  'location' : string,
  'timeSlot' : string,
}
export type NotificationId = bigint;
export interface NotificationRecord {
  'id' : NotificationId,
  'userId' : UserId,
  'notificationType' : NotificationType,
  'createdAt' : Timestamp,
  'read' : boolean,
  'message' : string,
}
export type NotificationType = { 'BookingCompleted' : null } |
  { 'CourseCompleted' : null } |
  { 'CourseEnrolled' : null } |
  { 'WorkDelivered' : null } |
  { 'GeneralInfo' : null } |
  { 'PaymentReceipt' : null } |
  { 'BookingConfirmed' : null } |
  { 'BookingReminder' : null };
export type PaymentAdminAction = { 'confirm' : null } |
  { 'adjustAmount' : bigint } |
  { 'refund' : null };
export type PaymentId = bigint;
export interface PaymentOrder {
  'id' : PaymentId,
  'signatureVerified' : boolean,
  'status' : PaymentStatus,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'referenceId' : string,
  'orderId' : string,
  'currency' : string,
  'paymentType' : PaymentType,
  'stripePaymentIntentId' : [] | [string],
  'checkoutUrl' : [] | [string],
  'stripeSessionId' : [] | [string],
  'amount' : bigint,
  'adminNotes' : [] | [string],
  'verifiedAt' : [] | [Timestamp],
  'paidAt' : [] | [Timestamp],
}
export interface PaymentOrderExtended {
  'id' : PaymentId,
  'razorpayPaymentId' : [] | [string],
  'status' : string,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'referenceId' : string,
  'orderId' : string,
  'razorpayOrderId' : string,
  'currency' : string,
  'paymentType' : string,
  'selectedServices' : Array<SelectedServiceItem>,
  'amount' : bigint,
  'adminNotes' : [] | [string],
  'paidAt' : [] | [Timestamp],
}
export interface PaymentReceiptDetails {
  'clientEmail' : string,
  'referenceId' : string,
  'currency' : string,
  'clientPhone' : string,
  'paymentId' : string,
  'amount' : bigint,
  'paidAt' : string,
}
export type PaymentStatus = { 'Failed' : null } |
  { 'Refunded' : null } |
  { 'Paid' : null } |
  { 'Created' : null };
export type PaymentStatus__1 = { 'PartiallyPaid' : null } |
  { 'FullyPaid' : null } |
  { 'Overdue' : null } |
  { 'Pending' : null };
export type PaymentType = { 'BookingBalance' : null } |
  { 'CourseEnrollment' : null } |
  { 'BookingUpfront' : null };
export interface PaymentVerificationStatus {
  'signatureVerified' : boolean,
  'status' : PaymentStatus,
  'orderId' : string,
  'paymentId' : PaymentId,
  'stripePaymentIntentId' : [] | [string],
  'stripeSessionId' : [] | [string],
  'verifiedAt' : [] | [Timestamp],
}
export interface SelectedServiceItem {
  'name' : string,
  'subServiceId' : string,
  'serviceId' : string,
  'price' : bigint,
}
export interface ServiceCategory {
  'id' : string,
  'subServices' : Array<SubService>,
  'icon' : string,
  'name' : string,
  'description' : string,
}
export interface ServiceRevenue {
  'serviceName' : string,
  'revenue' : bigint,
  'serviceId' : string,
  'bookingCount' : bigint,
}
export type SlotStatus = { 'Available' : null } |
  { 'Taken' : null };
export interface StripeConfirmation {
  'stripePaymentIntentId' : string,
  'stripeSessionId' : string,
}
export interface SubService { 'id' : string, 'name' : string }
export type TimeSlot = { 'Night' : null } |
  { 'Afternoon' : null } |
  { 'FullDay' : null } |
  { 'Morning' : null } |
  { 'Evening' : null } |
  { 'HalfDay' : null };
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserId = Principal;
export interface UserProfile {
  'status' : UserStatus,
  'created' : Timestamp,
  'principal' : UserId,
  'name' : string,
  'role' : UserRole,
  'email' : [] | [string],
  'phone' : string,
}
export type UserRole = { 'Staff' : null } |
  { 'Client' : null } |
  { 'Student' : null } |
  { 'Receptionist' : null } |
  { 'Admin' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type UserStatus = { 'Active' : null } |
  { 'Suspended' : null } |
  { 'Pending' : null };
export interface WhatsAppLog {
  'id' : bigint,
  'createdAt' : Timestamp,
  'sent' : boolean,
  'message' : string,
  'phone' : string,
  'relatedId' : [] | [string],
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addFeedback' : ActorMethod<
    [string, FeedbackTargetType, bigint, string],
    Feedback
  >,
  'adminAdjustAmount' : ActorMethod<[PaymentId, bigint, string], boolean>,
  'adminConfirmPayment' : ActorMethod<[PaymentId, string], boolean>,
  'adminGetAllPayments' : ActorMethod<[], Array<PaymentOrder>>,
  'adminRefundPayment' : ActorMethod<[PaymentId, string], boolean>,
  'adminUpdatePayment' : ActorMethod<
    [PaymentId, PaymentAdminAction, [] | [string]],
    boolean
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'confirmBooking' : ActorMethod<[BookingId], boolean>,
  'confirmPayment' : ActorMethod<[StripeConfirmation], boolean>,
  'createBookingRequest' : ActorMethod<[BookingInput], BookingRequest>,
  'createMultiServiceBooking' : ActorMethod<
    [MultiServiceBookingInput],
    BookingId
  >,
  'createPaymentOrder' : ActorMethod<
    [bigint, string, PaymentType],
    PaymentOrder
  >,
  'createSystemNotification' : ActorMethod<
    [UserId, string, NotificationType],
    NotificationRecord
  >,
  'deleteCmsContent' : ActorMethod<[string], undefined>,
  'deleteMedia' : ActorMethod<[MediaId], boolean>,
  'deleteSubServiceImage' : ActorMethod<[string, string], undefined>,
  'enrollCourse' : ActorMethod<[CourseId], CourseEnrollment>,
  'generateCertificate' : ActorMethod<[EnrollmentId], Certificate>,
  'getAdminPaymentDashboard' : ActorMethod<[], Array<AdminPaymentEntry>>,
  'getAdminPayments' : ActorMethod<[], Array<PaymentOrderExtended>>,
  'getAllBookings' : ActorMethod<[], Array<BookingRequest>>,
  'getAllCmsContent' : ActorMethod<[], Array<CmsContent>>,
  'getAllCourses' : ActorMethod<[], Array<Course>>,
  'getAllEnrollments' : ActorMethod<[], Array<CourseEnrollment>>,
  'getAllFeedback' : ActorMethod<[], Array<Feedback>>,
  'getAllSubServiceImages' : ActorMethod<[], Array<[string, string]>>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getAnalytics' : ActorMethod<[], BookingStats>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getCertificate' : ActorMethod<[string], [] | [Certificate]>,
  'getCmsContent' : ActorMethod<[string], [] | [CmsContent]>,
  'getCourse' : ActorMethod<[CourseId], [] | [Course]>,
  'getEmailLogs' : ActorMethod<[], Array<EmailLog>>,
  'getFeedbackForTarget' : ActorMethod<[string], Array<Feedback>>,
  'getMediaItems' : ActorMethod<[[] | [string]], Array<MediaItem>>,
  'getMyBookings' : ActorMethod<[], Array<BookingRequest>>,
  'getMyEnrollments' : ActorMethod<[], Array<CourseEnrollment>>,
  'getMyFeedback' : ActorMethod<[], Array<Feedback>>,
  'getMyMultiServiceBookings' : ActorMethod<[], Array<MultiServiceBooking>>,
  'getMyNotifications' : ActorMethod<[], Array<NotificationRecord>>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getPaymentDetails' : ActorMethod<[PaymentId], [] | [PaymentOrderExtended]>,
  'getPaymentStatus' : ActorMethod<[bigint], [] | [PaymentVerificationStatus]>,
  'getPublicCalendar' : ActorMethod<[], Array<BookingSlot>>,
  'getServiceCategories' : ActorMethod<[], Array<ServiceCategory>>,
  'getSubServiceImage' : ActorMethod<[string, string], [] | [string]>,
  'getWhatsAppLogs' : ActorMethod<[], Array<WhatsAppLog>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listMyPayments' : ActorMethod<[], Array<PaymentOrder>>,
  'manageUser' : ActorMethod<[UserId, string], boolean>,
  'markEnrollmentPaid' : ActorMethod<[EnrollmentId], boolean>,
  'markNotificationRead' : ActorMethod<[NotificationId], boolean>,
  'markWorkDelivered' : ActorMethod<[BookingId], boolean>,
  'register' : ActorMethod<[string, string, UserRole], UserProfile>,
  'respondToFeedback' : ActorMethod<[bigint, string], boolean>,
  'saveCallerUserProfile' : ActorMethod<[string, string, UserRole], undefined>,
  'sendBookingConfirmation' : ActorMethod<[UserId, BookingDetails], boolean>,
  'sendCompletionMessage' : ActorMethod<
    [UserId, BookingDetails, string],
    boolean
  >,
  'sendPaymentReceipt' : ActorMethod<[UserId, PaymentReceiptDetails], boolean>,
  'sendProgressReminder' : ActorMethod<[UserId, BookingDetails], boolean>,
  'setCmsContent' : ActorMethod<[string, string, CmsContentType], undefined>,
  'setFeatured' : ActorMethod<[MediaId, boolean], boolean>,
  'setSubServiceImage' : ActorMethod<[string, string, string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'transformWhatsApp' : ActorMethod<
    [TransformationInput],
    TransformationOutput
  >,
  'triggerPaymentRequest' : ActorMethod<[BookingId, string], string>,
  'updateCourseProgress' : ActorMethod<[CourseId, boolean], boolean>,
  'updateProfile' : ActorMethod<[string, string], boolean>,
  'uploadMedia' : ActorMethod<[MediaInput], MediaItem>,
  'verifyCertificate' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];